### ISSUE TITLE
ERROR in RangeError: Maximum call stack size exceeded - Build Angular 4

### ISSUE THREAD

**Issue by juan9009** [angular/material2#10455]
This error comes out when I compile the project with `ng build --aot --build-optimizer`

ERROR in RangeError: Maximum call stack size exceeded
    at Function.from (native)
    at dedupeArray (/home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:16097:22)
    at flattenAndDedupeArray (/home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:16106:12)
    at CompileMetadataResolver.getNgModuleMetadata (/home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15445:13)
    at CompileMetadataResolver.getNgModuleSummary (/home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15358:52)
    at /home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15450:68
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (/home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15445:49)
    at CompileMetadataResolver.getNgModuleSummary (/home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15358:52)
    at /home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15450:68
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (/home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15445:49)
    at CompileMetadataResolver.getNgModuleSummary (/home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15358:52)
    at /home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15450:68
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (/home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15445:49)
    at CompileMetadataResolver.getNgModuleSummary (/home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15358:52)
    at /home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15450:68
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (/home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15445:49)
    at CompileMetadataResolver.getNgModuleSummary (/home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15358:52)
    at /home/juan/Proyectos/angular-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15450:68

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate. 

(this is a canned response)
