### ISSUE TITLE
[Tooltip] Electron tooltip animation error (Partial keyframes are not supported.)

### ISSUE THREAD

**Issue by T94T** [angular/material2#10748]
We are using angular material in one of our electron apps. There's an error when moving to another tooltip element while previous tooltip fad in animation is running.

```
ERROR DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at WebAnimationsPlayer._triggerWebAnimation (webpack-internal:///./node_modules/@angular/animations/esm5/browser.js:5803:52)
    at WebAnimationsPlayer._buildPlayer (webpack-internal:///./node_modules/@angular/animations/esm5/browser.js:5766:18)
    at WebAnimationsPlayer.play (webpack-internal:///./node_modules/@angular/animations/esm5/browser.js:5839:14)
```

Angular material: 5.2.4
Angular: 5.2.4
Electron: 1.8.4
macOS: 10.13.4

web-animations-js polyfills are enabled, also in native chrome browser everything works.

**Comment by matheusdavidson** [comment]
Same here, but for me the problem is with snackbar:

```
Invalid keyframe value for property transform: matrix(1, 0, 0, 1, 0, 47,3232)

ERROR DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at WebAnimationsPlayer.push../node_modules/@angular/animations/fesm5/browser.js.WebAnimationsPlayer._triggerWebAnimation (http://localhost:4200/vendor.js:5590:34)
    at WebAnimationsPlayer.push../node_modules/@angular/animations/fesm5/browser.js.WebAnimationsPlayer._buildPlayer (http://localhost:4200/vendor.js:5571:18)
    at WebAnimationsPlayer.push../node_modules/@angular/animations/fesm5/browser.js.WebAnimationsPlayer.play (http://localhost:4200/vendor.js:5596:14)
    at TransitionAnimationPlayer.push../node_modules/@angular/animations/fesm5/browser.js.TransitionAnimationPlayer.play (http://localhost:4200/vendor.js:4832:91)
    at http://localhost:4200/vendor.js:4612:20
    at Array.forEach (<anonymous>)
    at TransitionAnimationEngine.push../node_modules/@angular/animations/fesm5/browser.js.TransitionAnimationEngine._flushAnimations (http://localhost:4200/vendor.js:4605:21)
    at TransitionAnimationEngine.push../node_modules/@angular/animations/fesm5/browser.js.TransitionAnimationEngine.flush (http://localhost:4200/vendor.js:4269:32)
    at InjectableAnimationEngine.push../node_modules/@angular/animations/fesm5/browser.js.AnimationEngine.flush (http://localhost:4200/vendor.js:5106:32)
    at http://localhost:4200/vendor.js:56172:30
```

Also tried to install and add web-animations-js to polyfills

**Comment by matheusdavidson** [comment]
```
Angular CLI: 6.0.0
Node: 9.10.1
OS: darwin x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/.DS_Store                <error>
@angular/flex-layout              6.0.0-beta.15
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

**Comment by matheusdavidson** [comment]
Found a workaround to make it work with electron:
```new BrowserWindow({ webPreferences: { experimentalFeatures: true } })```

You have to turn ```experimentalFeatures``` on when creating the browser window.
Hope this help you as well @T94T

**Comment by T94T** [comment]
Thanks @matheusdavidson, we solved it by implementing your workaround.
