### ISSUE TITLE
Building release via Gulp fails on Windows

### ISSUE THREAD

**Issue by NCC1701M** [angular/material2#1129]
#### Bug, feature request, or proposal:

When I run `gulp build:release` it fails at `:build:components:ngc`
#### What is the expected behavior?

To run `build:release` without errors.
#### What is the current behavior?

```
[10:34:46] Using gulpfile c:\Entwicklung\Visual Studio Code\material2\gulpfile.js
[10:34:46] Starting 'build:release'...
[10:34:46] Starting 'clean'...
[10:34:46] Finished 'clean' after 361 ms
[10:34:46] Starting ':build:components:ts'...
[10:34:46] Starting ':build:components:assets'...
[10:34:46] Starting ':build:components:scss'...
[10:34:57] Finished ':build:components:assets' after 11 s
[10:34:58] Finished ':build:components:ts' after 12 s
[10:35:00] Finished ':build:components:scss' after 14 s
[10:35:00] Starting 'build:components'...
[10:35:00] Finished 'build:components' after 98 ms
[10:35:00] Starting ':build:components:ngc'...
binPath: C:\Entwicklung\Visual Studio Code\material2\node_modules\@angular\compiler-cli\src\main.js
args: ["-p","src\\lib"]
options: {}
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1012:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at Object.exports.spawn (child_process.js:372:9)
    at ../../tools/gulp/task_helpers.ts:86:40
    at ../../tools/gulp/task_helpers.ts:136:41
    at C:\Entwicklung\Visual Studio Code\material2\node_modules\resolve-bin\index.js:40:5
    at C:\Entwicklung\Visual Studio Code\material2\node_modules\find-parent-dir\index.js:25:26
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
```
#### What are the steps to reproduce?

Switch to the material2 root folder and run `gulp build:release`.
#### Which versions of Angular, Material, OS, browsers are affected?

OS: Microsoft Windows [Version 6.1.7601] -->Windows 7
Node: v6.3.1
Last fetched: 2016-08-29 07:20 UTC

**Comment by jmcgoldrick** [comment]
Weird one, can't seem to figure out what changed, this worked a few commits back, I'm sure it did...

As far as I can figure, it stems from Windows not knowing how to spawn a plain ol' javascript file from the command-line (in this case, the `main.js` in `angular-cli/src`) - changing to the following in `execTask` works because it runs the js with node.

`const childProcess = child_process.spawn("node", [binPath].concat(args));`

I guess I don't quite understand what `execNodeTask` is good for, even after reading the code/comments because using `ngc` seems to work fine, @hansl will know what's up I am sure!

**Comment by rowantervelde** [comment]
Same problem over here. Seems like child_process.spawn is throwing an error:

```
==== execTask ====
binPath:  c:\Users\rowan\Documents\Code\material2\node_modules\@angular\compiler-cli\src\main.js
args:  [ '-p', 'src\\lib\\tsconfig.json' ]
options:  {}
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1036:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:380:9)
    at ../../tools/gulp/task_helpers.ts:131:40
    at ../../tools/gulp/task_helpers.ts:192:41
    at c:\Users\rowan\Documents\Code\material2\node_modules\resolve-bin\index.js:40:5
    at c:\Users\rowan\Documents\Code\material2\node_modules\find-parent-dir\index.js:25:26
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
```

**Comment by radarsu** [comment]
Also have this problem.

**Comment by rowantervelde** [comment]
Workaround by using module[ cross-spawn](https://www.npmjs.com/package/cross-spawn) and replacing following in task_helper.ts fixed problem on windows. Don't know if it still works on non-windows.

```
    const spawn = require('cross-spawn');
    const childProcess = spawn(binPath, args);
    //const childProcess = child_process.spawn(binPath, args);
```
