### ISSUE TITLE
matTooltip: this._ariaDescriber.removeDescription is not a function

### ISSUE THREAD

**Issue by didyk** [angular/material2#11389]
#### Bug, feature request, or proposal:
MatTooltip return error "this._ariaDescriber.removeDescription is not a function" on the server side.

#### What is the expected behavior?
MatTooltip work without error on server side.

#### What is the current behavior?
MatTooltip return error "this._ariaDescriber.removeDescription is not a function" on server side.

#### What are the steps to reproduce?
Start to render a page with two or more matSelect on the server side.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular : 6.0
Material: 6.0

**Comment by didyk** [comment]
@crisbeto full stack trace:
`ERROR TypeError: this._ariaDescriber.removeDescription is not a function
at MatTooltip.set [as message] (/usr/src/app/server/server.js:219808:33)
at updateProp (/usr/src/app/server/server.js:15266:37)
at checkAndUpdateDirectiveInline (/usr/src/app/server/server.js:15017:19)
at checkAndUpdateNodeInline (/usr/src/app/server/server.js:16326:20)
at checkAndUpdateNode (/usr/src/app/server/server.js:16288:16)
at prodCheckAndUpdateNode (/usr/src/app/server/server.js:16832:5)
at Object.Of.t.ɵvid.e [as updateDirectives] (/usr/src/app/server/server.js:127276:851229)
at Object.updateDirectives (/usr/src/app/server/server.js:16618:29)
at checkAndUpdateView (/usr/src/app/server/server.js:16270:14)
at callViewAction (/usr/src/app/server/server.js:16511:21)
`

**Comment by patrickmichalina** [comment]
same issue here

**Comment by didyk** [comment]
Update: 
This is reproduced without matTooltip on the page, only with mattooltip module

**Comment by Trysor** [comment]
This issue is still a problem, after 6.3.0:

```
ERROR TypeError: this._ariaDescriber.removeDescription is not a function
    at MatTooltip.set [as message] (..\dist\server.js:173123:33)
    at updateProp (..\dist\server.js:13058:37)
    at checkAndUpdateDirectiveInline (..\dist\server.js:12813:19)
    at checkAndUpdateNodeInline (..\dist\server.js:14116:20)
    at checkAndUpdateNode (..\dist\server.js:14078:16)
    at prodCheckAndUpdateNode (..\dist\server.js:14618:5)
    at Object.updateDirectives (..\dist\server.js:126106:606)
    at Object.updateDirectives (..\dist\server.js:14407:72)
    at checkAndUpdateView (..\dist\server.js:14060:14)
    at callViewAction (..\dist\server.js:14301:21)
```


```
TypeError: this._ariaDescriber.removeDescription is not a function
    at MatTooltip.ngOnDestroy (..\dist\server.js:173182:29)
    at callProviderLifecycles (..\dist\server.js:13175:18)
    at callElementProvidersLifecycles (..\dist\server.js:13143:13)
    at callLifecycleHooksChildrenFirst (..\dist\server.js:13133:29)
    at destroyView (..\dist\server.js:14195:5)
    at callViewAction (..\dist\server.js:14321:13)
    at execEmbeddedViewsAction (..\dist\server.js:14264:17)
    at destroyView (..\dist\server.js:14193:5)
    at callViewAction (..\dist\server.js:14321:13)
    at execEmbeddedViewsAction (..\dist\server.js:14264:17)
```
