### ISSUE TITLE
ng update @angular/material throw errors

### ISSUE THREAD

**Issue by ofirrifo** [angular/material2#11648]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
- execute: `ng update @angular/material` to pass successfully
- in case of error let me now what should I do
- indication in the update process that somthing happend 
- error summary 

#### What is the current behavior?
execute: `ng update @angular/material` throw a lot of error 

Example of the error
```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at SwitchTemplateInputNamesWalker._visitDirectiveCallExpression (/Users/ofirf/dev/management/mgmt-console/angular_material_schematics-gk3Pyw/update/tslint/component-walker.js:40:50)
    at SwitchTemplateInputNamesWalker.visitNode (/Users/ofirf/dev/management/mgmt-console/angular_material_schematics-gk3Pyw/update/tslint/component-walker.js:30:22)
    at /Users/ofirf/dev/management/mgmt-console/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/Users/ofirf/dev/management/mgmt-console/node_modules/typescript/lib/typescript.js:13263:24)
    at Object.forEachChild (/Users/ofirf/dev/management/mgmt-console/node_modules/typescript/lib/typescript.js:13544:24)
    at SwitchTemplateInputNamesWalker.SyntaxWalker.walkChildren (/Users/ofirf/dev/management/mgmt-console/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at SwitchTemplateInputNamesWalker.SyntaxWalker.visitNode (/Users/ofirf/dev/management/mgmt-console/node_modules/tslint/lib/language/walker/syntaxWalker.js:530:22)
    at SwitchTemplateInputNamesWalker.visitNode (/Users/ofirf/dev/management/mgmt-console/angular_material_schematics-gk3Pyw/update/tslint/component-walker.js:33:15)
    at /Users/ofirf/dev/management/mgmt-console/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/ofirf/dev/management/mgmt-console/node_modules/typescript/lib/typescript.js:13272:30)
```

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular V6.0.3
upgrade Material from V^5.2.5 to V^6.0.0 
OS mac
typescript V2.7.2

**Comment by andrewseguin** [comment]
@ofirrifo Thanks for reporting the issue but unfortunately I cannot reproduce the issue

**Comment by mgol** [comment]
@andrewseguin I'm seeing it to as do other people. See #11571 for more details.
