### ISSUE TITLE
DevApp errors on the latest commits

### ISSUE THREAD

**Issue by Chan4077** [angular/material2#12050]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The devapp should be served without any errors in the console.

#### What is the current behavior?
When building the Angular CDK, there are errors on the `cdk:build:esm:tests` task:

```
edricchan@Edrics-Macbook-Pro:~/Desktop/Projects/material2$ $(npm bin)/gulp serve:devapp
[10:25:53] Using gulpfile ~/Desktop/Projects/material2/gulpfile.js
(node:1576) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[10:25:53] Starting 'build:devapp'...
[10:25:53] Starting 'cdk:build-no-bundles'...
[10:25:53] Starting 'cdk:build:esm:tests'...
[10:25:53] Starting 'cdk:assets:scss'...
[10:25:53] Starting 'cdk:assets:es5-scss'...
[10:25:53] Starting 'cdk:assets:copy-styles'...
[10:25:53] Starting 'cdk:assets:html'...
[10:25:54] Finished 'cdk:assets:html' after 64 ms
[10:25:54] Finished 'cdk:assets:scss' after 146 ms
[10:25:54] Finished 'cdk:assets:es5-scss' after 137 ms
[10:25:54] Finished 'cdk:assets:copy-styles' after 139 ms
[10:25:54] Starting 'cdk:assets'...
[10:25:54] Finished 'cdk:assets' after 52 μs
Failed to compile  using /Users/edricchan/Desktop/Projects/material2/src/cdk/tsconfig-tests.json
[10:26:04] 'cdk:build:esm:tests' errored after 11 s
[10:26:04] Error: Failed to compile  using /Users/edricchan/Desktop/Projects/material2/src/cdk/tsconfig-tests.json
    at formatError (/Users/edricchan/Desktop/Projects/material2/node_modules/gulp-cli/lib/versioned/^3.7.0/formatError.js:20:10)
    at Gulp.<anonymous> (/Users/edricchan/Desktop/Projects/material2/node_modules/gulp-cli/lib/versioned/^3.7.0/log/events.js:41:15)
    at Gulp.emit (events.js:187:15)
    at Gulp.EventEmitter.emit (domain.js:442:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/edricchan/Desktop/Projects/material2/node_modules/orchestrator/index.js:264:8)
    at /Users/edricchan/Desktop/Projects/material2/node_modules/orchestrator/index.js:275:23
    at finish (/Users/edricchan/Desktop/Projects/material2/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/edricchan/Desktop/Projects/material2/node_modules/orchestrator/lib/runTask.js:45:4
    at process._tickCallback (internal/process/next_tick.js:68:7)
[10:26:04] 'build:devapp' errored after 11 s
[10:26:04] Error in plugin 'run-sequence(cdk:build:esm:tests)'
Message:
    Failed to compile  using /Users/edricchan/Desktop/Projects/material2/src/cdk/tsconfig-tests.json
Stack:
    at finish (/Users/edricchan/Desktop/Projects/material2/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/Users/edricchan/Desktop/Projects/material2/node_modules/run-sequence/index.js:67:4)
    at Gulp.emit (events.js:187:15)
    at Gulp.EventEmitter.emit (domain.js:442:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/edricchan/Desktop/Projects/material2/node_modules/orchestrator/index.js:264:8)
    at /Users/edricchan/Desktop/Projects/material2/node_modules/orchestrator/index.js:275:23
    at finish (/Users/edricchan/Desktop/Projects/material2/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/edricchan/Desktop/Projects/material2/node_modules/orchestrator/lib/runTask.js:45:4
    at process._tickCallback (internal/process/next_tick.js:68:7)
[10:26:04] 'cdk:build-no-bundles' errored after 11 s
[10:26:04] Error in plugin 'run-sequence(build:devapp)'
Message:
    Failed to compile  using /Users/edricchan/Desktop/Projects/material2/src/cdk/tsconfig-tests.json
Stack:
    at finish (/Users/edricchan/Desktop/Projects/material2/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/Users/edricchan/Desktop/Projects/material2/node_modules/run-sequence/index.js:67:4)
    at Gulp.emit (events.js:187:15)
    at Gulp.EventEmitter.emit (domain.js:442:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/edricchan/Desktop/Projects/material2/node_modules/orchestrator/index.js:264:8)
    at /Users/edricchan/Desktop/Projects/material2/node_modules/orchestrator/index.js:275:23
    at finish (/Users/edricchan/Desktop/Projects/material2/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/edricchan/Desktop/Projects/material2/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/edricchan/Desktop/Projects/material2/node_modules/run-sequence/index.js:60:5)
    at Gulp.onError (/Users/edricchan/Desktop/Projects/material2/node_modules/run-sequence/index.js:67:4)
[10:26:04] 'cdk:build-no-bundles' errored after 11 s
[10:26:04] Error in plugin 'run-sequence(cdk:build:esm:tests)'
Message:
    Failed to compile  using /Users/edricchan/Desktop/Projects/material2/src/cdk/tsconfig-tests.json
Stack:
    at finish (/Users/edricchan/Desktop/Projects/material2/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/Users/edricchan/Desktop/Projects/material2/node_modules/run-sequence/index.js:67:4)
    at Gulp.emit (events.js:187:15)
    at Gulp.EventEmitter.emit (domain.js:442:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/edricchan/Desktop/Projects/material2/node_modules/orchestrator/index.js:264:8)
    at /Users/edricchan/Desktop/Projects/material2/node_modules/orchestrator/index.js:275:23
    at finish (/Users/edricchan/Desktop/Projects/material2/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/edricchan/Desktop/Projects/material2/node_modules/orchestrator/lib/runTask.js:45:4
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
None

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
- Angular 6
- Angular Material `6.3.2` (latest commit)
- macOS Mojave 10.14 Beta (18A314k)

#### Is there anything else we should know?
This issue seems to be similar to #9469.

**Comment by crisbeto** [comment]
Everything works fine for me with the latest master, even after clearing my `node_modules`. It sounds like there might be something wrong with your environment.

**Comment by jelbourn** [comment]
Closing since we aren't seeing this ourselves

**Comment by Chan4077** [comment]
Seems that the recloning of the repository has fixed the problem. Thanks anyway!
