### ISSUE TITLE
mat-table and server side rendering (Angular Universal)

### ISSUE THREAD

**Issue by twoheaded** [angular/material2#12094]
#### Bug, feature request, or proposal:

bug

#### What is the expected behavior?

`mat-table` must be renderred on the server side by Angular Universal

#### What is the current behavior?

```
ERROR TypeError: Cannot read property 'classList' of undefined
    at StickyStyler._addStickyStyle (\dist\server.js:124832:17)
    at StickyStyler.updateStickyFooterContainer (\dist\server.js:124770:18)
    at MatTable.CdkTable.updateStickyFooterRowStyles (\dist\server.js:125600:28)
    at MatTable.CdkTable._forceRenderFooterRows (\dist\server.js:125903:14)
    at MatTable.CdkTable.ngAfterContentChecked (\dist\server.js:125272:18)
    at callProviderLifecycles (\dist\server.js:13208:18)
    at callElementProvidersLifecycles (dist\server.js:13186:13)
    at callLifecycleHooksChildrenFirst (\dist\server.js:13176:29)
    at checkAndUpdateView (\dist\server.js:14107:5)
    at callViewAction (\dist\server.js:14344:21)

```

#### What are the steps to reproduce?

StackBlitz reproduction is not possible.

Just сreate a simple app with `mat-table` and configure SSR according to this [guide](https://angular.io/guide/universal)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```
Angular CLI: 6.0.8
Node: 8.9.3
OS: win32 x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.3.2
@angular/cli                      6.0.8
@angular/material                 6.3.2
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

```

**Comment by ruant** [comment]
I know this is fixed in 7.0.0-beta.0, but is there a workaround for earlier versions?

I don't specify sticky in my code, and I get into this exact issue while rendering server side.
Or is sticky defaulting to true?
(That's another "issue" I have, the API documentation is rarely mentioning default values which is quite annoying)
