### ISSUE TITLE
Custom theme breaking on 6.4.4 release

### ISSUE THREAD

**Issue by dburt4** [angular/material2#12658]
#### Bug
Build failure with custom theme. 

#### What is the expected behavior?
Build should succeed as it does in version 6.4.3. 

#### What is the current behavior?
When running a build command on the latest version of Angular Material version (6.4.4), we get an odd scss error. 

```
ERROR in ./src/styles/customMaterialTheme.scss
Module build failed: ModuleBuildError: Module build failed: 
  600: #6.4.4-499458c1,
      ^
      Invalid CSS after "  600:": expected expression (e.g. 1px, bold), was "#6.4.4-499458c1,"
      in C:\Users\I20796\Documents\MyProjects\geomniDashboard\dashboard\DashboardView\node_modules\@angular\material\_theming.scss (line 1051, column 8)
    at runLoaders (C:\Users\I20796\Documents\MyProjects\geomniDashboard\dashboard\DashboardView\node_modules\webpack\lib\NormalModule.js:252:20)
    at C:\Users\I20796\Documents\MyProjects\geomniDashboard\dashboard\DashboardView\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Users\I20796\Documents\MyProjects\geomniDashboard\dashboard\DashboardView\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (C:\Users\I20796\Documents\MyProjects\geomniDashboard\dashboard\DashboardView\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (C:\Users\I20796\Documents\MyProjects\geomniDashboard\dashboard\DashboardView\node_modules\sass-loader\lib\loader.js:67:13)
    at Object.done [as callback] (C:\Users\I20796\Documents\MyProjects\geomniDashboard\dashboard\DashboardView\node_modules\neo-async\async.js:7974:18)
    at options.error (C:\Users\I20796\Documents\MyProjects\geomniDashboard\dashboard\DashboardView\node_modules\node-sass\lib\index.js:294:32)

```

#### What are the steps to reproduce?

Here is the related code to our custom theme.

Our cusomMaterialTheme.scss - taken largely from the examples:
```
//Taken from https://material.angular.io/guide/theming

@import '~@angular/material/theming';
@import 'variables';

@include mat-core();

$app-primary: mat-palette($mat-light-blue);
$app-accent:  mat-palette($mat-light-green, A200, A100, A400);

$app-warn:    mat-palette($mat-light-red);

$my-app-theme: mat-light-theme($app-primary, $app-accent, $app-warn);

@include angular-material-theme($my-app-theme);
```
And then in our _variables.scss file, we define a few custom mat theme color palettes. Here is an example of one: 

```
$mat-light-blue: (
  50: $blue,
  100: $blue,
  200: #1c8aca, //Lighter
  300: $blue,
  400: $blue, 
  500: $blue,
  600: #125c87, //Darker
  700: $blue,
  800: $blue,
  900: $blue,
  A100: $blue,
  A200: $blue,
  A400: $blue,
  A700: $blue,
  contrast: (
    50: $dark-primary-text,
    100: $dark-primary-text,
    200: $dark-primary-text,
    300: $dark-primary-text,
    400: $dark-primary-text,
    500: $light-primary-text,
    600: $light-primary-text,
    700: $light-primary-text,
    800: $light-primary-text,
    900: $light-primary-text,
    A100: $dark-primary-text,
    A200: $dark-primary-text,
    A400: $dark-primary-text,
    A700: $light-primary-text,
  )
);
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.4.4-499458c (in the error we're getting...?!)
Angular Material: 6.4.4
typescripe: 2.7.2

**Comment by josephperrott** [comment]
Can you try clearing your `node_modules` directory and installing again with `6.4.5`, as `6.4.4` was unpublished and superceded by `6.4.5`
