### ISSUE TITLE
How to ng  serve this repo

### ISSUE THREAD

**Issue by 8155220** [angular/material2#13781]
I have tried : 
git clone https://github.com/angular/material2.git
npm install 
ng serve 

I have got this error : 
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (C:\Users\Shep\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (C:\Users\Shep\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:24:21)
    at ServeCommand._loadWorkspaceAndArchitect (C:\Users\Shep\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:180:32)
    at ServeCommand.<anonymous> (C:\Users\Shep\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at C:\Users\Shep\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Shep\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:3:12)
    at ServeCommand.initialize (C:\Users\Shep\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:46:16)
    at Object.<anonymous> (C:\Users\Shep\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:87:23)

ng -v :

Angular CLI: 6.0.8
Node: 8.11.3
OS: win32 x64
Angular: 7.0.0-rc.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8 (cli-only)
@angular-devkit/core         0.6.8 (cli-only)
@angular-devkit/schematics   0.6.8 (cli-only)
@schematics/angular          0.6.8 (cli-only)
@schematics/update           0.6.8 (cli-only)
rxjs                         6.3.3
typescript                   3.1.1

**Comment by crisbeto** [comment]
We're not using the CLI. You can run `npm run demo-app` to run our dev app.
