### ISSUE TITLE
Failed to execute 'animate' on 'Element': Partial keyframes are not supported.

### ISSUE THREAD

**Issue by kondapaturisrinivasarao** [angular/material2#13970]
core.js:1673 ERROR DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at WebAnimationsPlayer.push../node_modules/@angular/animations/fesm5/browser.js.WebAnimationsPlayer._triggerWebAnimation (http://localhost:4200/vendor.js:5545:34)
    at WebAnimationsPlayer.push../node_modules/@angular/animations/fesm5/browser.js.WebAnimationsPlayer._buildPlayer (http://localhost:4200/vendor.js:5528:18)
    at WebAnimationsPlayer.push../node_modules/@angular/animations/fesm5/browser.js.WebAnimationsPlayer.play (http://localhost:4200/vendor.js:5551:14)
    at TransitionAnimationPlayer.push../node_modules/@angular/animations/fesm5/browser.js.TransitionAnimationPlayer.play (http://localhost:4200/vendor.js:4809:91)
    at http://localhost:4200/vendor.js:4589:20
    at Array.forEach (<anonymous>)
    at TransitionAnimationEngine.push../node_modules/@angular/animations/fesm5/browser.js.TransitionAnimationEngine._flushAnimations (http://localhost:4200/vendor.js:4582:21)
    at TransitionAnimationEngine.push../node_modules/@angular/animations/fesm5/browser.js.TransitionAnimationEngine.flush (http://localhost:4200/vendor.js:4231:32)
    at InjectableAnimationEngine.push../node_modules/@angular/animations/fesm5/browser.js.AnimationEngine.flush (http://localhost:4200/vendor.js:5079:32)
    at http://localhost:4200/vendor.js:63957:30

**Comment by kondapaturisrinivasarao** [comment]
I had  translateX(0) instead of translateX(0px)
translateX(100) and translateX(100px)

**Comment by kondapaturisrinivasarao** [comment]
Resolved
