### ISSUE TITLE
Issue With RippleRenderer when Using with Universal

### ISSUE THREAD

**Issue by antonyRoberts** [angular/material2#1415]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Material Should Render on Server 

#### What is the current behavior?
`EXCEPTION: document is not defined
ORIGINAL STACKTRACE:
ReferenceError: document is not defined
    at new RippleRenderer (P:\UniversalSports\node_modules\@angular\material\material.umd.js:193:31)
    at new MdRipple (P:\UniversalSports\node_modules\@angular\material\material.umd.js:327:32)
    at AppView._View_MdButton1.createInternal (MdButton.ngfactory.js:63:24)
    at AppView.create (P:\UniversalSports\node_modules\@angular\core\bundles\core.umd.js:9419:25)
    at TemplateRef_.createEmbeddedView (P:\UniversalSports\node_modules\@angular\core\bundles\core.umd.js:7510:18)
    at ViewContainerRef_.createEmbeddedView (P:\UniversalSports\node_modules\@angular\core\bundles\core.umd.js:5297:39)
    at NgIf.set [as ngIf] (P:\UniversalSports\node_modules\@angular\common\bundles\common.umd.js:1849:41)
    at AppView._View_MdButton0.detectChangesInternal (MdButton.ngfactory.js:42:25)
    at AppView.detectChanges (P:\UniversalSports\node_modules\@angular\core\bundles\core.umd.js:9566:18)
    at AppView.detectViewChildrenChanges (P:\UniversalSports\node_modules\@angular\core\bundles\core.umd.js:9592:23)
    at AppView._View_LoginComponent0.detectChangesInternal (LoginComponent.ngfactory.js:151:8)
    at AppView.detectChanges (P:\UniversalSports\node_modules\@angular\core\bundles\core.umd.js:9566:18)
    at AppView.detectViewChildrenChanges (P:\UniversalSports\node_modules\@angular\core\bundles\core.umd.js:9592:23)
    at AppView.detectChangesInternal (P:\UniversalSports\node_modules\@angular\core\bundles\core.umd.js:9577:18)
    at AppView.detectChanges (P:\UniversalSports\node_modules\@angular\core\bundles\core.umd.js:9566:18)
    at AppView.detectContentChildrenChanges (P:\UniversalSports\node_modules\@angular\core\bundles\core.umd.js:9584:23)
    at AppView._View_AppComponent0.detectChangesInternal (AppComponent.ngfactory.js:76:8)
    at AppView.detectChanges (P:\UniversalSports\node_modules\@angular\core\bundles\core.umd.js:9566:18)
    at AppView.detectViewChildrenChanges (P:\UniversalSports\node_modules\@angular\core\bundles\core.umd.js:9592:23)
    at AppView.detectChangesInternal (P:\UniversalSports\node_modules\@angular\core\bundles\core.umd.js:9577:18)
    at AppView.detectChanges (P:\UniversalSports\node_modules\@angular\core\bundles\core.umd.js:9566:18)
    at ViewRef_.detectChanges (P:\UniversalSports\node_modules\@angular\core\bundles\core.umd.js:7668:24)`

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### Which versions of Angular, Material, OS, browsers are affected?
Universal, Material 2.0.0-alpha.9

#### Is there anything else we should know?
@gdi2290 makes mention at the end of  https://github.com/angular/universal-starter/issues/185

**Comment by jelbourn** [comment]
See #308 (which tracks material working with Angular Universal)
