### ISSUE TITLE
gulp commands log no output

### ISSUE THREAD

**Issue by fxck** [angular/material2#1545]
At the current master(fresh clone), doing `npm run demo-app` prints this 

```
Treating 'rxjs/add/operator/first' as external dependency
material2 Admin$ No name was provided for external module 'rxjs/add/operator/first' in options.globals – guessing 'rxjs_add_operator_first'
```

then nothing, when I fix it(https://github.com/angular/material2/pull/1529), it just doesn't do anything at all no success message, no error message, nothing.

Using osx with these versions of gulp and node:

```
material2 Admin$ gulp -v
[18:41:05] CLI version 3.9.1
[18:41:05] Local version 3.9.1
material2 Admin$ node -v
v6.5.0
```

![image](https://cloud.githubusercontent.com/assets/1303561/19569162/0aa631b8-96f5-11e6-97bf-0ad4fe7fd8d8.png)

**Comment by fxck** [comment]
Ok, now it suddenly started throwing errors, this was in the log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'demo-app' ]
2 info using npm@3.8.9
3 info using node@v6.5.0
4 verbose run-script [ 'predemo-app', 'demo-app', 'postdemo-app' ]
5 info lifecycle material2@2.0.0-alpha.9-3~predemo-app: material2@2.0.0-alpha.9-3
6 silly lifecycle material2@2.0.0-alpha.9-3~predemo-app: no script for predemo-app, continuing
7 info lifecycle material2@2.0.0-alpha.9-3~demo-app: material2@2.0.0-alpha.9-3
8 verbose lifecycle material2@2.0.0-alpha.9-3~demo-app: unsafe-perm in lifecycle true
9 verbose lifecycle material2@2.0.0-alpha.9-3~demo-app: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Admin/www/material2/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle material2@2.0.0-alpha.9-3~demo-app: CWD: /Users/Admin/www/material2
11 silly lifecycle material2@2.0.0-alpha.9-3~demo-app: Args: [ '-c', 'gulp serve:devapp' ]
12 silly lifecycle material2@2.0.0-alpha.9-3~demo-app: Returned: code: 1  signal: null
13 info lifecycle material2@2.0.0-alpha.9-3~demo-app: Failed to exec demo-app script
14 verbose stack Error: material2@2.0.0-alpha.9-3 demo-app: `gulp serve:devapp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid material2@2.0.0-alpha.9-3
16 verbose cwd /Users/Admin/www/material2
17 error Darwin 15.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "demo-app"
19 error node v6.5.0
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error material2@2.0.0-alpha.9-3 demo-app: `gulp serve:devapp`
22 error Exit status 1
23 error Failed at the material2@2.0.0-alpha.9-3 demo-app script 'gulp serve:devapp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the material2 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp serve:devapp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs material2
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls material2
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by nkwood** [comment]
> then nothing, when I fix it(#1529), it just doesn't do anything at all no success message, no error message, nothing.

Did you try `localhost:4200`? I have the same console output shown in your screen cap after running `npm run demo-app` (there is no success message), however gulp does successfully start the demo app at port 4200.

**Comment by jelbourn** [comment]
This started happening to me too; they're working, but they're not _printing_ anything.

**Comment by mniya** [comment]
you should install gulp-cli,`sudo npm install -g gulp-cli`
