### ISSUE TITLE
Master causing errors with AOT

### ISSUE THREAD

**Issue by code-tree** [angular/material2#1592]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

I can use master with my AOT app
#### What is the current behavior?

When running `ngc` in my app.

```
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /home/jon/files/dev/src_platform_web/angular/root/root.module.ts, resolving symbol AppModule in /home/jon/files/dev/src_platform_web/angular/root/root.module.ts
    at simplifyInContext (/home/jon/files/dev/src_platform_web/node_modules/@angular/compiler-cli/src/static_reflector.js:469:23)
    at StaticReflector.simplify (/home/jon/files/dev/src_platform_web/node_modules/@angular/compiler-cli/src/static_reflector.js:472:22)
    at StaticReflector.annotations (/home/jon/files/dev/src_platform_web/node_modules/@angular/compiler-cli/src/static_reflector.js:61:36)
    at _loop_1 (/home/jon/files/dev/src_platform_web/node_modules/@angular/compiler-cli/src/codegen.js:53:54)
    at CodeGenerator.readFileMetadata (/home/jon/files/dev/src_platform_web/node_modules/@angular/compiler-cli/src/codegen.js:66:13)
    at /home/jon/files/dev/src_platform_web/node_modules/@angular/compiler-cli/src/codegen.js:100:74
    at Array.map (native)
    at CodeGenerator.codegen (/home/jon/files/dev/src_platform_web/node_modules/@angular/compiler-cli/src/codegen.js:100:35)
    at codegen (/home/jon/files/dev/src_platform_web/node_modules/@angular/compiler-cli/src/main.js:7:81)
    at Object.main (/home/jon/files/dev/src_platform_web/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
Compilation failed
```
#### What are the steps to reproduce?
1. Checkout master 1ad457b1b6e8853ba77ed8741a7b349a3fe3afb9
2. `npm install` & `gulp build:components`
3. `ngc` (in app)
#### Which versions of Angular, Material, OS, browsers are affected?

```
{
  "dependencies": {
    "@angular/common": "^2.1.0",
    "@angular/compiler": "^2.1.0",
    "@angular/compiler-cli": "^0.6.2",
    "@angular/core": "^2.1.0",
    "@angular/forms": "^2.1.0",
    "@angular/http": "^2.1.0",
    "@angular/platform-browser": "^2.1.0",
    "@angular/platform-server": "^2.1.0",
    "@angular/router": "^3.1.0",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.0.0-beta.12",
    "web-animations-js": "^2.2.2",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/core-js": "^0.9.34",
    "@types/node": "^6.0.41",
    "autoprefixer": "^6.5.1",
    "awesome-typescript-loader": "^2.2.4",
    "babel-core": "^6.14.0",
    "babel-plugin-transform-async-to-generator": "^6.8.0",
    "babel-preset-es2015": "^6.14.0",
    "file-loader": "^0.9.0",
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-autoprefixer": "^3.1.1",
    "gulp-exit": "0.0.2",
    "gulp-htmlmin": "^3.0.0",
    "gulp-if": "^2.0.1",
    "gulp-if-else": "^1.0.3",
    "gulp-insert": "^0.5.0",
    "gulp-intercept": "^0.1.0",
    "gulp-nunjucks": "^2.3.0",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.3.2",
    "gulp-typescript": "^3.0.1",
    "gulp-uglify": "^2.0.0",
    "html-minifier": "^3.1.0",
    "jinja-loader": "0.0.6",
    "js-yaml": "^3.6.1",
    "material-design-icons": "^2.1.1",
    "node-sass": "^3.10.1",
    "nunjucks": "^2.5.2",
    "nunjucks-html-loader": "^1.0.0",
    "nunjucks-loader": "^2.4.4",
    "postcss-cli": "^2.6.0",
    "rollup": "^0.36.3",
    "rollup-plugin-commonjs": "^5.0.4",
    "rollup-plugin-node-resolve": "^2.0.0",
    "rollup-plugin-string": "^2.0.2",
    "rollup-plugin-uglify": "^1.0.1",
    "typescript": "^2.0.3",
    "typings": "^1.3.3",
    "uglify-js": "^2.7.3"
  }
}
```
#### Is there anything else we should know?

App builds just fine when using `2.0.0-alpha.9-3` from npm.

This is my AppModule:

```
@NgModule({
    'imports': [
        BrowserModule, 
        MaterialModule.forRoot(), 
        CoreModule,  
        ViewModule,
        PlayerModule, 
        SharedModule,
        RoutesModule,
        SettingsModule,
    ],
    'declarations': [RootComp],
    'bootstrap': [RootComp],
})
export class AppModule {}
```

**Comment by RoxKilly** [comment]
That error probably means that one of your references cannot be statically resolved (ie: it's the result of a function)

Look through your `export` statements for a function call, and replace it with a static export.  I faced a very similar error and  in `app.routes.ts` for my App, I had to change how I export my routes from:
```
export const appRoutingComponents:any[] = 
           appRoutes.filter(r => !! r.component).map(r => r.component);
```
to:
```
export const appRoutingComponents:any[] = [
    HelpComponent,  LoginComponent, RegisterComponent
];
```

**Comment by code-tree** [comment]
Thanks @RoxKilly, I've also had this problem before with something else. However, I'm fairly sure it's not my code that's doing it, as the error does not occur when I use `2.0.0-alpha.9-3` from NPM. It only occurs when I try to use Material from master.

That would mean it is something in Material since `2.0.0-alpha.9-3` (I assume)?

**Comment by jelbourn** [comment]
@code-tree I cannot reproduce this- are you able to share your project?

**Comment by code-tree** [comment]
I'm now having problems even upgrading to next npm release. I assume this issue is a symptom of a bigger problem, so closing.
