### ISSUE TITLE
[md-input] pipe  cannot set args

### ISSUE THREAD

**Issue by keryhu** [angular/material2#1648]
#### Bug, feature request, or proposal:

bug
#### What is the current behavior?

t=new Date();

in html:

`<md-input value={{t|date}}>   </md-input>`

 //  can work

`<md-input value={{t|date:"MM/dd/yy"}}></md-input>`

// has errors. 
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the _best_ way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd
#### Which versions of Angular, Material, OS, browsers are affected?

angular2  2.1.1  material: 2.0.0-alpha.9-3

**Comment by jelbourn** [comment]
@keryhu What are the errors?

**Comment by keryhu** [comment]
Uncaught Error: Template parse errors:
Unexpected closing tag "md-input" ("
</p>
<hr>
<md-input value={{t|date:"MM/dd/yy"}}>[ERROR ->]</md-input>
"): HomeComponent@4:38
    at DirectiveNormalizer.normalizeLoadedTemplate (http://localhost:4200/main.bundle.js:29466:19)
    at DirectiveNormalizer.normalizeTemplateSync (http://localhost:4200/main.bundle.js:29453:21)
    at DirectiveNormalizer.normalizeDirective (http://localhost:4200/main.bundle.js:29429:43)
    at RuntimeCompiler._createCompiledTemplate (http://localhost:4200/main.bundle.js:50786:167)
    at http://localhost:4200/main.bundle.js:50714:41
    at Array.forEach (native)
    at http://localhost:4200/main.bundle.js:50710:48
    at Array.forEach (native)
    at RuntimeCompiler._compileComponents (http://localhost:4200/main.bundle.js:50709:43)
    at RuntimeCompiler._compileModuleAndComponents (http://localhost:4200/main.bundle.js:50645:37)

**Comment by jelbourn** [comment]
@vicb based on the syntax in the original comment, is that _supposed_ to work?

@keryhu doing a binding on `value` will probably work much better (and is the preferred syntax):
```html
<md-input [value]="t | date:'MM/dd/yy'"></md-input>
```

**Comment by keryhu** [comment]
oh .. it works ,thanks

**Comment by vicb** [comment]
Both the syntaxes are strictly equivalent:

```html
<input [value]="t | date:'MM/dd/yy'"></input>
<input value="{{t | date:'MM/dd/yy'}}"></input>
```

Note the `input` - I have verified in a plunker w/o md. But given the error and that `{{t|date}}` works it was most certainly an error in the original template (unclosed or extra tags).

**Comment by mmalerba** [comment]
both syntaxes seem to work now
