### ISSUE TITLE
Add travis validations for AoT compilation

### ISSUE THREAD

**Issue by d3viant0ne** [angular/material2#2120]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Release packages are usable with AoT compilation 

#### What is the current behavior?
In this particular case with the newly pushed alpha.11 package.

```
$ ./node_modules/.bin/ngc -p tsconfig.aot.json && yarn run rimraf -- output 
can't resolve module ./autosize from /home/ubuntu/jtx-ngrx-client/node_modules/@angular/material/input/input.d.ts
Error: Cannot read property 'MdTextareaAutosize' of undefined, resolving symbol MdInputModule in /home/ubuntu/jtx-ngrx-client/node_modules/@angular/material/input/input.d.ts, resolving symbol MdInputModule in /home/ubuntu/jtx-ngrx-client/node_modules/@angular/material/input/input.d.ts
    at simplifyInContext (/home/ubuntu/jtx-ngrx-client/node_modules/@angular/compiler-cli/src/static_reflector.js:475:23)
    at StaticReflector.simplify (/home/ubuntu/jtx-ngrx-client/node_modules/@angular/compiler-cli/src/static_reflector.js:478:22)
    at StaticReflector.annotations (/home/ubuntu/jtx-ngrx-client/node_modules/@angular/compiler-cli/src/static_reflector.js:60:36)
    at NgModuleResolver.resolve (/home/ubuntu/jtx-ngrx-client/node_modules/@angular/compiler/bundles/compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (/home/ubuntu/jtx-ngrx-client/node_modules/@angular/compiler/bundles/compiler.umd.js:14646:45)
    at CompileMetadataResolver._loadNgModuleSummary (/home/ubuntu/jtx-ngrx-client/node_modules/@angular/compiler/bundles/compiler.umd.js:14615:33)
    at /home/ubuntu/jtx-ngrx-client/node_modules/@angular/compiler/bundles/compiler.umd.js:14673:57
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (/home/ubuntu/jtx-ngrx-client/node_modules/@angular/compiler/bundles/compiler.umd.js:14660:51)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/home/ubuntu/jtx-ngrx-client/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
Compilation failed
```

#### What is the use-case or motivation for changing an existing behavior?
As opposed to creating issues each time something is released and a single component throws when run through ngc. Add a simple travis task in the matrix that runs the project through ngc. Doesn't need to be a time / resource consuming full validation run at first, just adding the compile step would be enough to catch most of the problems before they are published.

#### Which versions of Angular, Material, OS, browsers are affected?
`@angular/material-2.0.0-alpha.11`

#### Is there anything else we should know?

Happy to do the work assuming the proposal is acceptable

**Comment by jelbourn** [comment]
@d3viant0ne AoT _is_ part of our presubmit process, it just happens on Google's internal tooling instead of on Travis. I tried to add it to Travis as well, but ran into an issue with `ngc` (https://github.com/angular/angular/issues/12249).

That said, I can reproduce this. Something strange is going on with the npm package, investigating...

**Comment by d3viant0ne** [comment]
Fair enough, thanks.

**Comment by jelbourn** [comment]
@d3viant0ne figured out the problem. Seems to be a bug in `ngc` that was _supposed_ to be fixed, but apparently is still in some cases. Only affects builds consuming the `npm` package. Publishing a fix now...

**Comment by jelbourn** [comment]
@d3viant0ne just published alpha.11-1 that should fix this.

**Comment by d3viant0ne** [comment]
Thanks @jelbourn - AoT works fine now.
