### ISSUE TITLE
AOT compile failing with alpha-11 and ancular-cli 

### ISSUE THREAD

**Issue by mbellezi** [angular/material2#2185]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
alpha-11 AOT should compile.
alpha-10 compiles normally.

#### What is the current behavior?
When compiling with AOT, getting the error:

```
> ng build --watch --prod --aot 

  0% compiling
 10% building modules 2/2 modules 0 activecan't resolve module ./autosize from /Users/mbellezi/Documents/Projetos/relacionamento/client/node_modules/@angular/material/input/input.d.ts
Error: Cannot read property 'MdTextareaAutosize' of undefined, resolving symbol MdInputModule in /Users/mbellezi/Documents/Projetos/relacionamento/client/node_modules/@angular/material/input/input.d.ts, resolving symbol MdInputModule in /Users/mbellezi/Documents/Projetos/relacionamento/client/node_modules/@angular/material/input/input.d.ts
    at simplifyInContext (/Users/vsavkin/projects/angular/modules/@angular/compiler-cli/src/static_reflector.ts:537:15)
    at StaticReflector.simplify (/Users/vsavkin/projects/angular/modules/@angular/compiler-cli/src/static_reflector.ts:541:20)
    at StaticReflector.annotations (/Users/vsavkin/projects/angular/modules/@angular/compiler-cli/src/static_reflector.ts:93:28)
    at NgModuleResolver.resolve (/Users/mbellezi/Documents/Projetos/relacionamento/client/node_modules/@angular/compiler/bundles/compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (/Users/mbellezi/Documents/Projetos/relacionamento/client/node_modules/@angular/compiler/bundles/compiler.umd.js:14646:45)
    at CompileMetadataResolver._loadNgModuleSummary (/Users/mbellezi/Documents/Projetos/relacionamento/client/node_modules/@angular/compiler/bundles/compiler.umd.js:14615:33)
    at /Users/mbellezi/Documents/Projetos/relacionamento/client/node_modules/@angular/compiler/bundles/compiler.umd.js:14673:57
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (/Users/mbellezi/Documents/Projetos/relacionamento/client/node_modules/@angular/compiler/bundles/compiler.umd.js:14660:51)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/Users/mbellezi/Documents/Projetos/relacionamento/client/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/Users/mbellezi/Documents/Projetos/relacionamento/client/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /Users/mbellezi/Documents/Projetos/relacionamento/client/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/Users/mbellezi/Documents/Projetos/relacionamento/client/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)
    at analyzeNgModules (/Users/mbellezi/Documents/Projetos/relacionamento/client/node_modules/@angular/compiler/bundles/compiler.umd.js:12700:16)
    at analyzeAndValidateNgModules (/Users/mbellezi/Documents/Projetos/relacionamento/client/node_modules/@angular/compiler/bundles/compiler.umd.js:12704:20)
    at OfflineCompiler.compileModules (/Users/mbellezi/Documents/Projetos/relacionamento/client/node_modules/@angular/compiler/bundles/compiler.umd.js:12775:20)
    at CodeGenerator.codegen (/Users/vsavkin/projects/angular/modules/@angular/compiler-cli/src/codegen.ts:71:26)
    at /Users/mbellezi/Documents/Projetos/relacionamento/client/node_modules/@ngtools/webpack/src/plugin.js:210:73
    at process._tickCallback (internal/process/next_tick.js:103:7)

```

#### What are the steps to reproduce?

run:  ng build --watch --prod --aot 

#### Which versions of Angular, Material, OS, browsers are affected?
macOS: 10.12.1
@angular-cli-beta-21
@angular-2.2.3
@angular/material-alpha-11

#### Is there anything else we should know?

alpha-10 compiles without problem

**Comment by mbellezi** [comment]
alpha-11-1 fixed it.

**Comment by andrewseguin** [comment]
alpha-11-1 had some problems with AoT as well, use alpha-11-2
