### ISSUE TITLE
Error: Hammer.js is not loaded, can not bind slidestart event

### ISSUE THREAD

**Issue by HomeboxJim** [angular/material2#2357]
#### Bug, feature request, or proposal:
bug

I put ` <md-slide-toggle></md-slide-toggle>` in my html markup and get this error:

```
error_handler.js:45 EXCEPTION: Uncaught (in promise): Error: Error in ./MdSlideToggle class MdSlideToggle - inline template:0:809 caused by: Hammer.js is not loaded, can not bind slidestart event
Error: Hammer.js is not loaded, can not bind slidestart event
    at HammerGesturesPlugin.supports (http://localhost:4200/main.bundle.js:34107:19)
    at EventManager._findPluginFor (http://localhost:4200/main.bundle.js:12964:24)
    at EventManager.addEventListener (http://localhost:4200/main.bundle.js:12951:27)
    at DomRenderer.listen (http://localhost:4200/main.bundle.js:33907:48)
    at DebugDomRenderer.listen (http://localhost:4200/main.bundle.js:66572:31)
    at _View_MdSlideToggle0.createInternal (MdSlideToggle.ngfactory.js:71:36)
    at _View_MdSlideToggle0.AppView.create (http://localhost:4200/main.bundle.js:67922:21)
    at _View_MdSlideToggle0.DebugAppView.create (http://localhost:4200/main.bundle.js:68134:44)
    at _View_MyProfilePageComponent0.createInternal (MyProfilePageComponent.ngfactory.js:278:15)
    at _View_MyProfilePageComponent0.AppView.create (http://localhost:4200/main.bundle.js:67922:21)
ErrorHandler.handleError @ error_handler.js:45
next @ application_ref.js:273
schedulerFn @ async.js:82
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:74
onError @ ng_zone.js:120
onHandleError @ ng_zone_impl.js:64
ZoneDelegate.handleError @ zone.js:236
Zone.runGuarded @ zone.js:131
_loop_1 @ zone.js:412
drainMicroTaskQueue @ zone.js:421
ZoneTask.invoke @ zone.js:339
error_handler.js:50 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:50
next @ application_ref.js:273
schedulerFn @ async.js:82
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:74
onError @ ng_zone.js:120
onHandleError @ ng_zone_impl.js:64
ZoneDelegate.handleError @ zone.js:236
Zone.runGuarded @ zone.js:131
_loop_1 @ zone.js:412
drainMicroTaskQueue @ zone.js:421
ZoneTask.invoke @ zone.js:339
error_handler.js:51 Error: Uncaught (in promise): Error: Error in ./MdSlideToggle class MdSlideToggle - inline template:0:809 caused by: Hammer.js is not loaded, can not bind slidestart event
Error: Hammer.js is not loaded, can not bind slidestart event
    at HammerGesturesPlugin.supports (hammer_gestures.js:57)
    at EventManager._findPluginFor (event_manager.js:37)
    at EventManager.addEventListener (event_manager.js:24)
    at DomRenderer.listen (dom_renderer.js:156)
    at DebugDomRenderer.listen (debug_renderer.js:87)
    at _View_MdSlideToggle0.createInternal (MdSlideToggle.ngfactory.js:71)
    at _View_MdSlideToggle0.AppView.create (view.js:125)
    at _View_MdSlideToggle0.DebugAppView.create (view.js:337)
    at _View_MyProfilePageComponent0.createInternal (MyProfilePageComponent.ngfactory.js:278)
    at _View_MyProfilePageComponent0.AppView.create (view.js:125)
    at resolvePromise (zone.js:468)
    at zone.js:445
    at ZoneDelegate.invoke (zone.js:232)
    at Object.onInvoke (ng_zone_impl.js:43)
    at ZoneDelegate.invoke (zone.js:231)
    at Zone.run (zone.js:114)
    at zone.js:502
    at ZoneDelegate.invokeTask (zone.js:265)
    at Object.onInvokeTask (ng_zone_impl.js:34)
    at ZoneDelegate.invokeTask (zone.js:264)
ErrorHandler.handleError @ error_handler.js:51
next @ application_ref.js:273
schedulerFn @ async.js:82
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:74
onError @ ng_zone.js:120
onHandleError @ ng_zone_impl.js:64
ZoneDelegate.handleError @ zone.js:236
Zone.runGuarded @ zone.js:131
_loop_1 @ zone.js:412
drainMicroTaskQueue @ zone.js:421
ZoneTask.invoke @ zone.js:339
zone.js:388 Unhandled Promise rejection: Error in ./MdSlideToggle class MdSlideToggle - inline template:0:809 caused by: Hammer.js is not loaded, can not bind slidestart event ; Zone: angular ; Task: Promise.then ; Value: ViewWrappedError {_nativeError: Error: Error in ./MdSlideToggle class MdSlideToggle - inline template:0:809 caused by: Hammer.js is …, originalError: Error: Hammer.js is not loaded, can not bind slidestart event
    at HammerGesturesPlugin.supports (…, context: DebugContext} Error: Hammer.js is not loaded, can not bind slidestart event
    at HammerGesturesPlugin.supports (http://localhost:4200/main.bundle.js:34107:19)
    at EventManager._findPluginFor (http://localhost:4200/main.bundle.js:12964:24)
    at EventManager.addEventListener (http://localhost:4200/main.bundle.js:12951:27)
    at DomRenderer.listen (http://localhost:4200/main.bundle.js:33907:48)
    at DebugDomRenderer.listen (http://localhost:4200/main.bundle.js:66572:31)
    at _View_MdSlideToggle0.createInternal (MdSlideToggle.ngfactory.js:71:36)
    at _View_MdSlideToggle0.AppView.create (http://localhost:4200/main.bundle.js:67922:21)
    at _View_MdSlideToggle0.DebugAppView.create (http://localhost:4200/main.bundle.js:68134:44)
    at _View_MyProfilePageComponent0.createInternal (MyProfilePageComponent.ngfactory.js:278:15)
    at _View_MyProfilePageComponent0.AppView.create (http://localhost:4200/main.bundle.js:67922:21)
consoleError @ zone.js:388
_loop_1 @ zone.js:417
drainMicroTaskQueue @ zone.js:421
ZoneTask.invoke @ zone.js:339
zone.js:390 Error: Uncaught (in promise): Error: Error in ./MdSlideToggle class MdSlideToggle - inline template:0:809 caused by: Hammer.js is not loaded, can not bind slidestart event
Error: Hammer.js is not loaded, can not bind slidestart event
    at HammerGesturesPlugin.supports (hammer_gestures.js:57)
    at EventManager._findPluginFor (event_manager.js:37)
    at EventManager.addEventListener (event_manager.js:24)
    at DomRenderer.listen (dom_renderer.js:156)
    at DebugDomRenderer.listen (debug_renderer.js:87)
    at _View_MdSlideToggle0.createInternal (MdSlideToggle.ngfactory.js:71)
    at _View_MdSlideToggle0.AppView.create (view.js:125)
    at _View_MdSlideToggle0.DebugAppView.create (view.js:337)
    at _View_MyProfilePageComponent0.createInternal (MyProfilePageComponent.ngfactory.js:278)
    at _View_MyProfilePageComponent0.AppView.create (view.js:125)
    at HammerGesturesPlugin.supports (hammer_gestures.js:57)
    at EventManager._findPluginFor (event_manager.js:37)
    at EventManager.addEventListener (event_manager.js:24)
    at DomRenderer.listen (dom_renderer.js:156)
    at DebugDomRenderer.listen (debug_renderer.js:87)
    at _View_MdSlideToggle0.createInternal (MdSlideToggle.ngfactory.js:71)
    at _View_MdSlideToggle0.AppView.create (view.js:125)
    at _View_MdSlideToggle0.DebugAppView.create (view.js:337)
    at _View_MyProfilePageComponent0.createInternal (MyProfilePageComponent.ngfactory.js:278)
    at _View_MyProfilePageComponent0.AppView.create (view.js:125)
    at resolvePromise (zone.js:468)
    at zone.js:445
    at ZoneDelegate.invoke (zone.js:232)
    at Object.onInvoke (ng_zone_impl.js:43)
    at ZoneDelegate.invoke (zone.js:231)
    at Zone.run (zone.js:114)
    at zone.js:502
    at ZoneDelegate.invokeTask (zone.js:265)
    at Object.onInvokeTask (ng_zone_impl.js:34)
    at ZoneDelegate.invokeTask (zone.js:264)
```

![cypher_city](https://cloud.githubusercontent.com/assets/21176220/21440613/cf88a522-c861-11e6-80e2-c3e2d26e0ea8.png)

angular-cli: 1.0.0-beta.15
node: 6.9.2
os: darwin x64
@angular 2.0.0

**Comment by crisbeto** [comment]
There's a fix in the next version that should make HammerJS optional, although you should keep in mind that some of the sliding gestures won't work.

**Comment by crisbeto** [comment]
This should be resolved if you update to the latest Material version.

**Comment by sandeepgosavi** [comment]
Add this line in head <script src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.js"></script>
