### ISSUE TITLE
npm run demo-app dies with illegal operation

### ISSUE THREAD

**Issue by paceto256** [angular/material2#2488]
Trying to run material2 demo app on Ubuntu 16.04

1. git checkout material2repo ...
2. npm run build
3. npm run demo-app

here is the log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/local/bin/npm', 'run', 'demo-app' ]
2 info using npm@4.0.5
3 info using node@v6.9.2
4 verbose run-script [ 'predemo-app', 'demo-app', 'postdemo-app' ]
5 info lifecycle material2@2.0.0-beta.1~predemo-app: material2@2.0.0-beta.1
6 silly lifecycle material2@2.0.0-beta.1~predemo-app: no script for predemo-app, continuing
7 info lifecycle material2@2.0.0-beta.1~demo-app: material2@2.0.0-beta.1
8 verbose lifecycle material2@2.0.0-beta.1~demo-app: unsafe-perm in lifecycle true
9 verbose lifecycle material2@2.0.0-beta.1~demo-app: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/paceto/proj/material2/node_modules/.bin:/home/paceto/bin:/home/paceto/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
10 verbose lifecycle material2@2.0.0-beta.1~demo-app: CWD: /home/paceto/proj/material2
11 silly lifecycle material2@2.0.0-beta.1~demo-app: Args: [ '-c', 'gulp serve:devapp' ]
12 silly lifecycle material2@2.0.0-beta.1~demo-app: Returned: code: 1  signal: null
13 info lifecycle material2@2.0.0-beta.1~demo-app: Failed to exec demo-app script
14 verbose stack Error: material2@2.0.0-beta.1 demo-app: `gulp serve:devapp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid material2@2.0.0-beta.1
16 verbose cwd /home/paceto/proj/material2
17 error Linux 4.4.0-57-generic
18 error argv "/usr/bin/nodejs" "/usr/local/bin/npm" "run" "demo-app"
19 error node v6.9.2
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error material2@2.0.0-beta.1 demo-app: `gulp serve:devapp`
22 error Exit status 1
23 error Failed at the material2@2.0.0-beta.1 demo-app script 'gulp serve:devapp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the material2 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp serve:devapp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs material2
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls material2
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by paceto256** [comment]
I checkout fresh copy from git rebuild and the issue was gone.
Probably some local issue, closing this "issue" :)
