### ISSUE TITLE
AOT prod build treeshaking - Compilation failed. Resource file not found - for @angular/material/core/core

### ISSUE THREAD

**Issue by yoda888** [angular/material2#2845]
#### Issue:
JIT build works as expected.
AOT prod enabled build cases the exceptions whereby  @angular/material/core/core is reported as 
Compilation failed. Resource file not found

#### What is the current behavior?
Build for prod targeted for AOT causes
Compilation failed. Resource file not found: <i removed the path>/node_modules/@angular/material/core/core
caused even with minimal  ngc -p
```
> del-cli public/js/app && ngc -p tsconfig.aot.json && ngc -p tsconfig.aot.json && webpack --config webpack.config.prod.js --progress --profile --bail && del-cli 'public/js/app/**/*.js' 'public/js/app/**/*.js.map' '!public/js/app/bundle.js' '!public/js/app/*.chun
k.js' 'assets/app/**/*.ngfactory.ts' 'assets/app/**/*.shim.ts'

Error: Compilation failed. Resource file not found: <removed-root-path>/node_modules/@angular/material/core/core
    at ModuleResolutionHostAdapter.readResource (<removed-root-path>\node_modules\@angular\compiler-cli\src\compiler_host.js:291:19)
    at CompilerHost.loadResource (<removed-root-path>\node_modules\@angular\compiler-cli\src\compiler_host.js:230:85)
    at Object.get (<removed-root-path>\node_modules\@angular\compiler\bundles\compiler.umd.js:26385:111)
    at DirectiveNormalizer._fetch (<removed-root-path>\node_modules\@angular\compiler\bundles\compiler.umd.js:13767:47)
    at<removed-root-path>\@angular\compiler\bundles\compiler.umd.js:13884:57
    at Array.map (native)
    at DirectiveNormalizer._loadMissingExternalStylesheets (<removed-root-path>\node_modules\@angular\compiler\bundles\compiler.umd.js:13884:18)
    at <removed-root-path>\node_modules\@angular\compiler\bundles\compiler.umd.js:13887:30
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
Compilation failed
```

#### What are the steps to reproduce?

tsconfig.aot
```{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "outDir": "./public/js/app"
  },
  "exclude": [
    "node_modules",
    "dist",
    "assets/app/polyfills.ts"
  ],
  "files": [
    "assets/app/app.module.ts",
    "assets/app/main.aot.ts"
  ],
  "angularCompilerOptions": {
    "skipMetadataEmit" : true
  }
}
```

main.aot
```
import './polyfills';

import 'rxjs/add/operator/map';
import 'rxjs/add/operator/do';
import { platformBrowser } from '@angular/platform-browser';
import { AppModuleNgFactory } from './app.module.ngfactory';
import { enableProdMode } from '@angular/core';
import 'hammerjs';

enableProdMode();

platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```

#### Which versions of Angular, Material, OS, browsers are affected?

```   "@angular/common": "^2.4.2",
    "@angular/compiler": "^2.4.2",
    "@angular/compiler-cli": "^2.0.0",
    "@angular/core": "^2.4.2",
    "@angular/material": "^2.0.0-beta.1",
```

**Comment by onurcipe** [comment]
Still having the same issue... Any news?

**Comment by NickvdMeij** [comment]
Also having this issue, seems like this is still a problem when running angular 2 with AoT compilation. Any1 got any idea why this error is thrown and possible how to fix it? Tried debugging it myself but cant figure out what the problem is...

**Comment by jelbourn** [comment]
Not sure what this error is, though the original report says beta.1, which could be an issue. Feel free to open a new issue with reproduction steps if this is still affecting anyone. Our docs site (https://github.com/angular/material.angular.io) uses the latest version of Material w/ AoT, so that may serve as an example.
