### ISSUE TITLE
Md Sidebar - EXCEPTION: Uncaught (in promise): Error: No provider for InteractivityChecker!

### ISSUE THREAD

**Issue by laurobd** [angular/material2#3213]
#### Bug, feature request, or proposal:
When I'm using this function:
  `(click)="start.toggle()"`
Inside:
  `<button md-button class="md-primary" (click)="start.toggle()">Sidenav 1</button>`
Which is in this code:
`import { Component } from '@angular/core';

@Component({
  template: \`
    <md-sidenav-container>

      <md-sidenav #start mode="side" align="start" opened="true">
        <cadastros-menu></cadastros-menu>
      </md-sidenav>

      <md-sidenav #end mode="side" align="end" opened="true">
        <p>sidenav 2 sidenav 2 sidenav 2</p>
      </md-sidenav>

      <div>
        <router-outlet></router-outlet>
  
        <button md-button class="md-primary" (click)="start.toggle()">Sidenav 1</button>
        <button md-button class="md-primary" (click)="end.toggle()">Sidenav 2</button>
      </div>

    </md-sidenav-container>
  `
})
export class CadastrosInit { }`

Everything is working, but I'm receiving a bug in my console log and I have no idea whats happening.

I'm using `MaterialModule.forRoot()` in the app module.

#### What is the expected behavior?
I cann't eliminate the exception below.

#### What is the current behavior?

I'm receiving this Exception back:

Listening on: http://localhost:3000
EXCEPTION: Uncaught (in promise): Error: No provider for InteractivityChecker!
Error: No provider for InteractivityChecker!
    at NoProviderError.Error (native)
    at NoProviderError.BaseError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:2889:34)
    at NoProviderError.AbstractProviderError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39662:16)
    at new NoProviderError (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39693:16)
    at ReflectiveInjector_._throwOrNull (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59765:19)
    at ReflectiveInjector_._getByKeyDefault (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59793:25)
    at ReflectiveInjector_._getByKey (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59756:25)
    at ReflectiveInjector_.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59565:21)
    at NgModuleInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:40571:52)
    at ElementInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59956:48)
ORIGINAL STACKTRACE:
Error: Uncaught (in promise): Error: No provider for InteractivityChecker!
Error: No provider for InteractivityChecker!
    at NoProviderError.Error (native)
    at NoProviderError.BaseError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:2889:34)
    at NoProviderError.AbstractProviderError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39662:16)
    at new NoProviderError (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39693:16)
    at ReflectiveInjector_._throwOrNull (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59765:19)
    at ReflectiveInjector_._getByKeyDefault (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59793:25)
    at ReflectiveInjector_._getByKey (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59756:25)
    at ReflectiveInjector_.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59565:21)
    at NgModuleInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:40571:52)
    at ElementInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59956:48)
    at resolvePromise (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\node_modules\zone.js\dist\zone-node.js:468:31)
    at C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\node_modules\zone.js\dist\zone-node.js:445:13
    at ZoneDelegate.invoke (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\node_modules\zone.js\dist\zone-node.js:232:26)
    at Object.onInvoke (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:27087:37)
    at ZoneDelegate.invoke (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\node_modules\zone.js\dist\zone-node.js:231:32)
    at Zone.run (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\node_modules\zone.js\dist\zone-node.js:114:43)
    at C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\node_modules\zone.js\dist\zone-node.js:502:57
    at ZoneDelegate.invokeTask (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\node_modules\zone.js\dist\zone-node.js:265:35)
    at Object.onInvokeTask (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:27078:37)
    at ZoneDelegate.invokeTask (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\node_modules\zone.js\dist\zone-node.js:264:40)
Unhandled Promise rejection: No provider for InteractivityChecker! ; Zone: angular ; Task: Promise.then ; Value: { Error: No provider for InteractivityChecker!
    at NoProviderError.Error (native)
    at NoProviderError.BaseError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:2889:34)
    at NoProviderError.AbstractProviderError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39662:16)
    at new NoProviderError (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39693:16)
    at ReflectiveInjector_._throwOrNull (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59765:19)
    at ReflectiveInjector_._getByKeyDefault (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59793:25)
    at ReflectiveInjector_._getByKey (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59756:25)
    at ReflectiveInjector_.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59565:21)
    at NgModuleInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:40571:52)
    at ElementInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59956:48)
  _nativeError:
   Error: No provider for InteractivityChecker!
       at NoProviderError.Error (native)
       at NoProviderError.BaseError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:2889:34)
       at NoProviderError.AbstractProviderError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39662:16)
       at new NoProviderError (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39693:16)
       at ReflectiveInjector_._throwOrNull (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59765:19)
       at ReflectiveInjector_._getByKeyDefault (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59793:25)
       at ReflectiveInjector_._getByKey (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59756:25)
       at ReflectiveInjector_.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59565:21)
       at NgModuleInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:40571:52)
       at ElementInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59956:48),
  keys: [ ReflectiveKey { token: [Function: InteractivityChecker], id: 48 } ],
  injectors:
   [ ReflectiveInjector_ {
       _constructionCounter: 1,
       _proto: [Object],
       _parent: [Object],
       _strategy: [Object] } ],
  constructResolvingMessage: [Function] } Error: No provider for InteractivityChecker!
    at NoProviderError.Error (native)
    at NoProviderError.BaseError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:2889:34)
    at NoProviderError.AbstractProviderError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39662:16)
    at new NoProviderError (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39693:16)
    at ReflectiveInjector_._throwOrNull (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59765:19)
    at ReflectiveInjector_._getByKeyDefault (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59793:25)
    at ReflectiveInjector_._getByKey (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59756:25)
    at ReflectiveInjector_.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59565:21)
    at NgModuleInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:40571:52)
    at ElementInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59956:48)
{ Error: Uncaught (in promise): Error: No provider for InteractivityChecker!
Error: No provider for InteractivityChecker!
    at NoProviderError.Error (native)
    at NoProviderError.BaseError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:2889:34)
    at NoProviderError.AbstractProviderError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39662:16)
    at new NoProviderError (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39693:16)
    at ReflectiveInjector_._throwOrNull (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59765:19)
    at ReflectiveInjector_._getByKeyDefault (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59793:25)
    at ReflectiveInjector_._getByKey (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59756:25)
    at ReflectiveInjector_.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59565:21)
    at NgModuleInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:40571:52)
    at ElementInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59956:48)
    at resolvePromise (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\node_modules\zone.js\dist\zone-node.js:468:31)
    at C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\node_modules\zone.js\dist\zone-node.js:445:13
    at ZoneDelegate.invoke (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\node_modules\zone.js\dist\zone-node.js:232:26)
    at Object.onInvoke (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:27087:37)
    at ZoneDelegate.invoke (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\node_modules\zone.js\dist\zone-node.js:231:32)
    at Zone.run (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\node_modules\zone.js\dist\zone-node.js:114:43)
    at C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\node_modules\zone.js\dist\zone-node.js:502:57
    at ZoneDelegate.invokeTask (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\node_modules\zone.js\dist\zone-node.js:265:35)
    at Object.onInvokeTask (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:27078:37)
    at ZoneDelegate.invokeTask (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\node_modules\zone.js\dist\zone-node.js:264:40)
  rejection:
   { Error: No provider for InteractivityChecker!
       at NoProviderError.Error (native)
       at NoProviderError.BaseError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:2889:34)
       at NoProviderError.AbstractProviderError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39662:16)
       at new NoProviderError (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39693:16)
       at ReflectiveInjector_._throwOrNull (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59765:19)
       at ReflectiveInjector_._getByKeyDefault (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59793:25)
       at ReflectiveInjector_._getByKey (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59756:25)
       at ReflectiveInjector_.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59565:21)
       at NgModuleInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:40571:52)
       at ElementInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59956:48)
     _nativeError:
      Error: No provider for InteractivityChecker!
          at NoProviderError.Error (native)
          at NoProviderError.BaseError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:2889:34)
          at NoProviderError.AbstractProviderError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39662:16)
          at new NoProviderError (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39693:16)
          at ReflectiveInjector_._throwOrNull (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59765:19)
          at ReflectiveInjector_._getByKeyDefault (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59793:25)
          at ReflectiveInjector_._getByKey (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59756:25)
          at ReflectiveInjector_.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59565:21)
          at NgModuleInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:40571:52)
          at ElementInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59956:48),
     keys: [ [Object] ],
     injectors: [ [Object] ],
     constructResolvingMessage: [Function] },
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value:
      { Error: No provider for InteractivityChecker!
          at NoProviderError.Error (native)
          at NoProviderError.BaseError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:2889:34)
          at NoProviderError.AbstractProviderError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39662:16)
          at new NoProviderError (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39693:16)
          at ReflectiveInjector_._throwOrNull (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59765:19)
          at ReflectiveInjector_._getByKeyDefault (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59793:25)
          at ReflectiveInjector_._getByKey (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59756:25)
          at ReflectiveInjector_.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59565:21)
          at NgModuleInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:40571:52)
          at ElementInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59956:48)
        _nativeError:
         Error: No provider for InteractivityChecker!
             at NoProviderError.Error (native)
             at NoProviderError.BaseError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:2889:34)
             at NoProviderError.AbstractProviderError [as constructor] (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39662:16)
             at new NoProviderError (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:39693:16)
             at ReflectiveInjector_._throwOrNull (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59765:19)
             at ReflectiveInjector_._getByKeyDefault (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59793:25)
             at ReflectiveInjector_._getByKey (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59756:25)
             at ReflectiveInjector_.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59565:21)
             at NgModuleInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:40571:52)
             at ElementInjector.get (C:\Users\lauro\Dropbox\00 Projeto ERP\Workspace\erp-app\dist\server\index.js:59956:48),
        keys: [Object],
        injectors: [Object],
        constructResolvingMessage: [Function] } },
  zone:
   Zone {
     _properties: { isAngularZone: true },
     _parent:
      Zone {
        _properties: [Object],
        _parent: [Object],
        _name: 'UNIVERSAL request',
        _zoneDelegate: [Object] },
     _name: 'angular',
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [Object],
        _forkZS: null,
        _forkDlgt: null,
        _interceptZS: null,
        _interceptDlgt: null,
        _invokeZS: [Object],
        _invokeDlgt: [Object],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [Object],
        _scheduleTaskZS: null,
        _scheduleTaskDlgt: null,
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [Object],
        _cancelTaskZS: null,
        _cancelTaskDlgt: null,
        _hasTaskZS: [Object],
        _hasTaskDlgt: [Object] } },
  task:
   ZoneTask {
     runCount: 1,
     type: 'microTask',
     zone:
      Zone {
        _properties: [Object],
        _parent: [Object],
        _name: 'angular',
        _zoneDelegate: [Object] },
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/core@~2.1.2
@angular/material@^2.0.0-beta.1
Windows 10 / Chrome browser

**Comment by kara** [comment]
Can you add a plunker repro case? We're not able to get it to fail with the code you provided:

http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview

**Comment by nebgor** [comment]
i got an error just like the issue title (not sure about trace) when i downgraded from beta.2 to beta.1 and forgot to change the import call back to  MaterialModule.forRoot() but doing so did resolve this for me.

**Comment by laurobd** [comment]
@kara, thanks for your help. It was an update issue. I had to update, not just the material to beta 2, but angular as well. Now it working fine.
