### ISSUE TITLE
input on lastest release does not work

### ISSUE THREAD

**Issue by davidmontgom** [angular/material2#3257]
WOW!!!! total fail... 

A form page Radio and selects works but wowee.....a simple input from the example fails from  the angular2 material page fails.  Using the lastest.  Rather concerned that a simple input causes so mush havoc.  Take the below out then page works find.  Tsk Tsk Tsk

                <md-input-container>
                    <input mdInput placeholder="Favorite food" value="Sushi">
                </md-input-container>

EXCEPTION: Uncaught (in promise): Error: Error in ./mesaHedgeInitialComponent class mesaHedgeInitialComponent - inline template:124:16 caused by: this._hintChildren.find is not a function
TypeError: this._hintChildren.find is not a function
    at MdInputContainer._syncAriaDescribedby (http://localhost:4200/main.bundle.js:35936:32)
    at MdInputContainer._processHints (http://localhost:4200/main.bundle.js:35902:14)
    at MdInputContainer.ngAfterContentInit (http://localhost:4200/main.bundle.js:35873:14)
    at _View_mesaHedgeInitialComponent0.detectChangesInternal (mesaHedgeInitialComponent.ngfactory.js:1234:68)
    at _View_mesaHedgeInitialComponent0.AppView.detectChanges (http://localhost:4200/main.bundle.js:81003:14)
    at _View_mesaHedgeInitialComponent0.DebugAppView.detectChanges (http://localhost:4200/main.bundle.js:81108:44)
    at _View_mesaHedgeInitialComponent_Host0.AppView.detectViewChildrenChanges (http://localhost:4200/main.bundle.js:81029:19)
    at _View_mesaHedgeInitialComponent_Host0.detectChangesInternal (mesaHedgeInitialComponent_Host.ngfactory.js:48:8)
    at _View_mesaHedgeInitialComponent_Host0.AppView.detectChanges (http://localhost:4200/main.bundle.js:81003:14)
    at _View_mesaHedgeInitialComponent_Host0.DebugAppView.detectChanges (http://localhost:4200/main.bundle.js:81108:44)
ErrorHandler.handleError @ error_handler.js:45
next @ application_ref.js:273
schedulerFn @ async.js:82
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:74
onError @ ng_zone.js:120
onHandleError @ ng_zone_impl.js:64
ZoneDelegate.handleError @ zone.js:236
Zone.runGuarded @ zone.js:131
_loop_1 @ zone.js:412
drainMicroTaskQueue @ zone.js:421
ZoneTask.invoke @ zone.js:339
error_handler.js:50 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:50
next @ application_ref.js:273
schedulerFn @ async.js:82
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:74
onError @ ng_zone.js:120
onHandleError @ ng_zone_impl.js:64
ZoneDelegate.handleError @ zone.js:236
Zone.runGuarded @ zone.js:131
_loop_1 @ zone.js:412
drainMicroTaskQueue @ zone.js:421
ZoneTask.invoke @ zone.js:339
error_handler.js:51 Error: Uncaught (in promise): Error: Error in ./mesaHedgeInitialComponent class mesaHedgeInitialComponent - inline template:124:16 caused by: this._hintChildren.find is not a function
TypeError: this._hintChildren.find is not a function
    at MdInputContainer._syncAriaDescribedby (input-container.js:371)
    at MdInputContainer._processHints (input-container.js:337)
    at MdInputContainer.ngAfterContentInit (input-container.js:308)
    at _View_mesaHedgeInitialComponent0.detectChangesInternal (mesaHedgeInitialComponent.ngfactory.js:1234)
    at _View_mesaHedgeInitialComponent0.AppView.detectChanges (view.js:272)
    at _View_mesaHedgeInitialComponent0.DebugAppView.detectChanges (view.js:377)
    at _View_mesaHedgeInitialComponent_Host0.AppView.detectViewChildrenChanges (view.js:298)
    at _View_mesaHedgeInitialComponent_Host0.detectChangesInternal (mesaHedgeInitialComponent_Host.ngfactory.js:48)
    at _View_mesaHedgeInitialComponent_Host0.AppView.detectChanges (view.js:272)
    at _View_mesaHedgeInitialComponent_Host0.DebugAppView.detectChanges (view.js:377)
    at resolvePromise (zone.js:468)
    at zone.js:445
    at ZoneDelegate.invoke (zone.js:232)
    at Object.onInvoke (ng_zone_impl.js:43)
    at ZoneDelegate.invoke (zone.js:231)
    at Zone.run (zone.js:114)
    at zone.js:502
    at ZoneDelegate.invokeTask (zone.js:265)
    at Object.onInvokeTask (ng_zone_impl.js:34)
    at ZoneDelegate.invokeTask (zone.js:264)
ErrorHandler.handleError @ error_handler.js:51
next @ application_ref.js:273
schedulerFn @ async.js:82
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:74
onError @ ng_zone.js:120
onHandleError @ ng_zone_impl.js:64
ZoneDelegate.handleError @ zone.js:236
Zone.runGuarded @ zone.js:131
_loop_1 @ zone.js:412
drainMicroTaskQueue @ zone.js:421
ZoneTask.invoke @ zone.js:339
zone.js:388 Unhandled Promise rejection: Error in ./mesaHedgeInitialComponent class mesaHedgeInitialComponent - inline template:124:16 caused by: this._hintChildren.find is not a function ; Zone: angular ; Task: Promise.then ; Value: ViewWrappedError {_nativeError: Error: Error in ./mesaHedgeInitialComponent class mesaHedgeInitialComponent - inline template:124:16…, originalError: TypeError: this._hintChildren.find is not a function
    at MdInputContainer._syncAriaDescribedby (h…, context: DebugContext} TypeError: this._hintChildren.find is not a function
    at MdInputContainer._syncAriaDescribedby (http://localhost:4200/main.bundle.js:35936:32)
    at MdInputContainer._processHints (http://localhost:4200/main.bundle.js:35902:14)
    at MdInputContainer.ngAfterContentInit (http://localhost:4200/main.bundle.js:35873:14)
    at _View_mesaHedgeInitialComponent0.detectChangesInternal (mesaHedgeInitialComponent.ngfactory.js:1234:68)
    at _View_mesaHedgeInitialComponent0.AppView.detectChanges (http://localhost:4200/main.bundle.js:81003:14)
    at _View_mesaHedgeInitialComponent0.DebugAppView.detectChanges (http://localhost:4200/main.bundle.js:81108:44)
    at _View_mesaHedgeInitialComponent_Host0.AppView.detectViewChildrenChanges (http://localhost:4200/main.bundle.js:81029:19)
    at _View_mesaHedgeInitialComponent_Host0.detectChangesInternal (mesaHedgeInitialComponent_Host.ngfactory.js:48:8)
    at _View_mesaHedgeInitialComponent_Host0.AppView.detectChanges (http://localhost:4200/main.bundle.js:81003:14)
    at _View_mesaHedgeInitialComponent_Host0.DebugAppView.detectChanges (http://localhost:4200/main.bundle.js:81108:44)
consoleError @ zone.js:388
_loop_1 @ zone.js:417
drainMicroTaskQueue @ zone.js:421
ZoneTask.invoke @ zone.js:339
zone.js:390 Error: Uncaught (in promise): Error: Error in ./mesaHedgeInitialComponent class mesaHedgeInitialComponent - inline template:124:16 caused by: this._hintChildren.find is not a function
TypeError: this._hintChildren.find is not a function
    at MdInputContainer._syncAriaDescribedby (input-container.js:371)
    at MdInputContainer._processHints (input-container.js:337)
    at MdInputContainer.ngAfterContentInit (input-container.js:308)
    at _View_mesaHedgeInitialComponent0.detectChangesInternal (mesaHedgeInitialComponent.ngfactory.js:1234)
    at _View_mesaHedgeInitialComponent0.AppView.detectChanges (view.js:272)
    at _View_mesaHedgeInitialComponent0.DebugAppView.detectChanges (view.js:377)
    at _View_mesaHedgeInitialComponent_Host0.AppView.detectViewChildrenChanges (view.js:298)
    at _View_mesaHedgeInitialComponent_Host0.detectChangesInternal (mesaHedgeInitialComponent_Host.ngfactory.js:48)
    at _View_mesaHedgeInitialComponent_Host0.AppView.detectChanges (view.js:272)
    at _View_mesaHedgeInitialComponent_Host0.DebugAppView.detectChanges (view.js:377)
    at MdInputContainer._syncAriaDescribedby (input-container.js:371)
    at MdInputContainer._processHints (input-container.js:337)
    at MdInputContainer.ngAfterContentInit (input-container.js:308)
    at _View_mesaHedgeInitialComponent0.detectChangesInternal (mesaHedgeInitialComponent.ngfactory.js:1234)
    at _View_mesaHedgeInitialComponent0.AppView.detectChanges (view.js:272)
    at _View_mesaHedgeInitialComponent0.DebugAppView.detectChanges (view.js:377)
    at _View_mesaHedgeInitialComponent_Host0.AppView.detectViewChildrenChanges (view.js:298)
    at _View_mesaHedgeInitialComponent_Host0.detectChangesInternal (mesaHedgeInitialComponent_Host.ngfactory.js:48)
    at _View_mesaHedgeInitialComponent_Host0.AppView.detectChanges (view.js:272)
    at _View_mesaHedgeInitialComponent_Host0.DebugAppView.detectChanges (view.js:377)
    at resolvePromise (zone.js:468)
    at zone.js:445
    at ZoneDelegate.invoke (zone.js:232)
    at Object.onInvoke (ng_zone_impl.js:43)
    at ZoneDelegate.invoke (zone.js:231)
    at Zone.run (zone.js:114)
    at zone.js:502
    at ZoneDelegate.invokeTask (zone.js:265)
    at Object.onInvokeTask (ng_zone_impl.js:34)
    at ZoneDelegate.invokeTask (zone.js:264)
consoleError @ zone.js:390
_loop_1 @ zone.js:417
drainMicroTaskQueue @ zone.js:421
ZoneTask.invoke @ zone.js:339

**Comment by crisbeto** [comment]
It looks like your Angular version is too old. Try updating to at least Angular 2.3.

**Comment by ottosson** [comment]
It's easy to get hurt at the bleeding edge ;)

**Comment by crisbeto** [comment]
Angular 2.3 has been out for a few months now, it's not particularly cutting edge. Closing since 2.3 is our minimum supported version as per the package.json.
