### ISSUE TITLE
Sample Apps not working

### ISSUE THREAD

**Issue by graham-sportsmgmt** [angular/material2#3363]
At the bottom of the Getting Started page ( https://material.angular.io/guide/getting-started ) there are links to two sample apps:

Material Sample App - https://material.angular.io/guide/material2-app
Angular Connect 2016 Demo - https://material.angular.io/guide/leashed-in

Both of these links redirect to https://material.angular.io/ which shows an eternal loading message:

![untitled](https://cloud.githubusercontent.com/assets/16939733/23476743/9fd884ba-fe70-11e6-9c1b-3ec605fd018b.png)

The console shows this error output:

```
TypeError: Cannot read property 'document' of undefined
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:28:9953)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at e.t.internalDetectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5542)
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:28:7809)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at t.detectChangesInNestedViews (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:57:780)
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:26:9934)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at e.t.internalDetectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5542)
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:26:8430)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:1008:1301)
    at https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:183:5180
    at Array.forEach (native)
    at e.tick (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:183:5147)
i @ vendor.cd86af5b77b0c0342f39.bundle.js:1417
vendor.cd86af5b77b0c0342f39.bundle.js:735 EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'document' of undefined
TypeError: Cannot read property 'document' of undefined
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:28:9953)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at e.t.internalDetectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5542)
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:28:7809)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:1008:1301)
    at t.activate (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:529:1918)
    at t.placeComponentIntoOutlet (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:14476)
    at t.activateRoutes (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:14064)
    at https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:13299
    at Array.forEach (native)
    at t.activateChildRoutes (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:13277)
    at t.activate (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:12934)
    at https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:7777
    at e._next (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:57:3070)
t.handleError @ vendor.cd86af5b77b0c0342f39.bundle.js:735
vendor.cd86af5b77b0c0342f39.bundle.js:735 ORIGINAL STACKTRACE:
t.handleError @ vendor.cd86af5b77b0c0342f39.bundle.js:735
vendor.cd86af5b77b0c0342f39.bundle.js:735 Error: Uncaught (in promise): TypeError: Cannot read property 'document' of undefined
TypeError: Cannot read property 'document' of undefined
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:28:9953)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at e.t.internalDetectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5542)
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:28:7809)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:1008:1301)
    at t.activate (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:529:1918)
    at t.placeComponentIntoOutlet (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:14476)
    at t.activateRoutes (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:14064)
    at https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:13299
    at Array.forEach (native)
    at t.activateChildRoutes (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:13277)
    at t.activate (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:12934)
    at https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:7777
    at e._next (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:57:3070)
    at m (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:1417:2213)
    at l (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:1417:1372)
    at l (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:1417:1121)
    at https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:1417:1776
    at t.invokeTask (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:1417:9670)
    at Object.onInvokeTask (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:78:2559)
    at t.invokeTask (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:1417:9591)
    at n.runTask (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:1417:5370)
    at o (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:1417:497)
t.handleError @ vendor.cd86af5b77b0c0342f39.bundle.js:735
vendor.cd86af5b77b0c0342f39.bundle.js:1417 Unhandled Promise rejection: Cannot read property 'document' of undefined ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'document' of undefined
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:28:9953)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at e.t.internalDetectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5542)
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:28:7809)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:1008:1301)
    at t.activate (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:529:1918)
    at t.placeComponentIntoOutlet (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:14476)
    at t.activateRoutes (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:14064)
    at https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:13299
    at Array.forEach (native)
    at t.activateChildRoutes (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:13277)
    at t.activate (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:12934)
    at https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:7777
    at e._next (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:57:3070) TypeError: Cannot read property 'document' of undefined
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:28:9953)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at e.t.internalDetectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5542)
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:28:7809)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:1008:1301)
    at t.activate (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:529:1918)
    at t.placeComponentIntoOutlet (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:14476)
    at t.activateRoutes (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:14064)
    at https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:13299
    at Array.forEach (native)
    at t.activateChildRoutes (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:13277)
    at t.activate (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:12934)
    at https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:7777
    at e._next (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:57:3070)
i @ vendor.cd86af5b77b0c0342f39.bundle.js:1417

```

**Comment by DevVersion** [comment]
Thanks for the issue. This has been fixed with SHA https://github.com/angular/material2/commit/cb57660981bee42fda8abc730e7f763ae357c598.

The correct links should show up within the next release of Angular Material.

**Comment by ssatguru** [comment]
still getting the same issue

**Comment by DevVersion** [comment]
There hasn't been a release yet. Coming soon,
