### ISSUE TITLE
gettin started demo doesnt work

### ISSUE THREAD

**Issue by etwillbefine** [angular/material2#3388]
#### Bug, feature request, or proposal:
material.angular.io gettin' started demo doesnt work

#### What is the expected behavior?
demo is shown

#### What is the current behavior?
```
Unhandled Promise rejection: Cannot read property 'document' of undefined ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'document' of undefined
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:28:9953)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at e.t.internalDetectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5542)
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:28:7809)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:1008:1301)
    at t.activate (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:529:1918)
    at t.placeComponentIntoOutlet (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:14476)
    at t.activateRoutes (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:14064)
    at https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:13299
    at Array.forEach (native)
    at t.activateChildRoutes (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:13277)
    at t.activate (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:12934)
    at https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:7777
    at e._next (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:57:3070) TypeError: Cannot read property 'document' of undefined
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:28:9953)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at e.t.internalDetectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5542)
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:28:7809)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:1008:1301)
    at t.activate (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:529:1918)
    at t.placeComponentIntoOutlet (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:14476)
    at t.activateRoutes (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:14064)
    at https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:13299
    at Array.forEach (native)
    at t.activateChildRoutes (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:13277)
    at t.activate (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:12934)
    at https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:162:7777
    at e._next (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:57:3070)
```

#### What are the steps to reproduce?
visit https://material.angular.io/guide/material2-app

#### Is there anything else we should know?
Chrome, 56.0.2924.87 (64-bit)
Mac Sierra

**Comment by kara** [comment]
See issue in docs site: https://github.com/angular/material.angular.io/issues/105

It's actually not a demo app, it's a link to a Github repo. The domain was copied incorrectly by our script. 

Correct link is http://github.com/jelbourn/material2-app

**Comment by etwillbefine** [comment]
Its linked on the following page at the buttom https://material.angular.io/guide/getting-started

**Comment by kara** [comment]
Yep, should be fixed when we next deploy the docs site.

**Comment by StefH** [comment]
Any update?
