### ISSUE TITLE
UnitTests not possible with MaterialComponents

### ISSUE THREAD

**Issue by Sabartius** [angular/material2#3391]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Unit-Tests should be runnable

#### What is the current behavior?
When writing UnitTests for Components that use Components from the MaterialModule, it crashes when TestBed resets the TestingModule

`TypeError: Cannot read property 'unsubscribe' of undefined
	    at ScrollDispatcher.deregister (webpack:///~/@angular/material/core/overlay/scroll/scroll-dispatcher.js:52:0 <- config/karma-test-shim.js:24402:50)
	    at Scrollable.ngOnDestroy (webpack:///~/@angular/material/core/overlay/scroll/scrollable.js:28:0 <- config/karma-test-shim.js:136759:22)
	    at Wrapper_Scrollable.ngOnDestroy (/OverlayModule/Scrollable/wrapper.ngfactory.js:13:16)
	    at CompiledTemplate.proxyViewClass.View_MdSidenavContainer0.destroyInternal (/MdSidenavModule/MdSidenavContainer/component.ngfactory.js:66:24)
	    at CompiledTemplate.proxyViewClass.AppView.destroy (webpack:///~/@angular/core/src/linker/view.js:203:0 <- config/karma-test-shim.js:132618:14)
	    at CompiledTemplate.proxyViewClass.DebugAppView.destroy (webpack:///~/@angular/core/src/linker/view.js:606:0 <- config/karma-test-shim.js:133021:38)
	    at CompiledTemplate.proxyViewClass.View_PruefvorgangsverwaltungApp0.destroyInternal (/DynamicTestModule/PruefvorgangsverwaltungApp/component.ngfactory.js:880:19)
	    at CompiledTemplate.proxyViewClass.AppView.destroy (webpack:///~/@angular/core/src/linker/view.js:203:0 <- config/karma-test-shim.js:132618:14)
	    at CompiledTemplate.proxyViewClass.DebugAppView.destroy (webpack:///~/@angular/core/src/linker/view.js:606:0 <- config/karma-test-shim.js:133021:38)
	    at CompiledTemplate.proxyViewClass.View_PruefvorgangsverwaltungApp_Host0.destroyInternal (/DynamicTestModule/PruefvorgangsverwaltungApp/host.ngfactory.js:39:19)
	    at CompiledTemplate.proxyViewClass.AppView.destroy (webpack:///~/@angular/core/src/linker/view.js:203:0 <- config/karma-test-shim.js:132618:14)
	    at CompiledTemplate.proxyViewClass.DebugAppView.destroy (webpack:///~/@angular/core/src/linker/view.js:606:0 <- config/karma-test-shim.js:133021:38)
	    at CompiledTemplate.proxyViewClass.AppView.detachAndDestroy (webpack:///~/@angular/core/src/linker/view.js:187:0 <- config/karma-test-shim.js:132602:14)
	    at ComponentRef_.destroy (webpack:///~/@angular/core/src/linker/component_factory.js:147:51 <- config/karma-test-shim.js:60572:70)
	    at ComponentFixture.destroy (webpack:///~/@angular/core/bundles/core-testing.umd.js:263:0 <- config/karma-test-shim.js:7042:35)
	    at webpack:///~/@angular/core/bundles/core-testing.umd.js:728:61 <- config/karma-test-shim.js:7507:78
	    at Array.forEach (native)
	    at TestBed.resetTestingModule (webpack:///~/@angular/core/bundles/core-testing.umd.js:728:0 <- config/karma-test-shim.js:7507:34)
	    at Function.TestBed.resetTestingModule (webpack:///~/@angular/core/bundles/core-testing.umd.js:636:0 <- config/karma-test-shim.js:7415:26)
	    at Object.<anonymous> (webpack:///~/@angular/core/bundles/core-testing.umd.js:967:0 <- config/karma-test-shim.js:7746:21)
	    at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:229:0 <- config/karma-test-shim.js:119404:26)
	    at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:79:0 <- config/karma-test-shim.js:119071:39)
	    at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:228:0 <- config/karma-test-shim.js:119403:32)
	    at Zone.run (webpack:///~/zone.js/dist/zone.js:113:0 <- config/karma-test-shim.js:119288:43)
	    at Object.<anonymous> (webpack:///~/zone.js/dist/jasmine-patch.js:102:0 <- config/karma-test-shim.js:118786:34)
	    at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (webpack:///~/zone.js/dist/jasmine-patch.js:132:0 <- config/karma-test-shim.js:118816:42)
	    at ZoneDelegate.invokeTask (webpack:///~/zone.js/dist/zone.js:262:0 <- config/karma-test-shim.js:119437:35)
	    at Zone.runTask (webpack:///~/zone.js/dist/zone.js:151:0 <- config/karma-test-shim.js:119326:47)
	    at drainMicroTaskQueue (webpack:///~/zone.js/dist/zone.js:405:0 <- config/karma-test-shim.js:119580:35)
`

#### What are the steps to reproduce?

Write a Karma-Test for a Component using a MaterialComponent like SideNav and calling `fixture.detectChanges()`, import MaterialModule and run the test

#### Which versions of Angular, Material, OS, browsers are affected?
Material Beta2

**Comment by Sabartius** [comment]
Here someone already described the Problem: http://stackoverflow.com/questions/42345925/angular2-material-md-sidenav-container-causes-exception-in-ng-test

**Comment by kara** [comment]
@Sabartius Can you provide some code from your test? We have many unit tests up and running for Material components in this repo, including sidenav, so it is probably specific to the test.

**Comment by neekers** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10211837-251917939_1-s1-v1.png?transparent=1&palette=1&width=246)

Happens to me too with just the default setup of sidebar nav and toolbar using angular cli generator.

**Comment by Sabartius** [comment]
@kara I created a new app using the angular-cli and installed material beta2.
The Component Code is quite simple: 

```html 
<md-sidenav-container>
  <h1>
    {{title}}
  </h1>
  <md-sidenav #sidenav>
  </md-sidenav>
</md-sidenav-container>
```

i ran the original tests created by the cli for the app component. the only change i made was importing the MaterialModule:
```typescript
import { TestBed, async } from '@angular/core/testing';
import { MaterialModule } from '@angular/material';

import { AppComponent } from './app.component';

describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      imports: [
        MaterialModule
      ]
    }).compileComponents();
  }));

  it('should create the app', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  }));

  it(`should have as title 'app works!'`, async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app.title).toEqual('app works!');
  }));

  it('should render title in a h1 tag', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelector('h1').textContent).toContain('app works!');
  }));
});
```

and there's the error again:
```
Chrome 56.0.2924 (Linux 0.0.0) AppComponent should render title in a h1 tag FAILED
	TypeError: Cannot read property 'unsubscribe' of undefined
	    at ScrollDispatcher.deregister (webpack:///~/@angular/material/core/overlay/scroll/scroll-dispatcher.js:52:0 <- src/test.ts:10758:50)
	    at Scrollable.ngOnDestroy (webpack:///~/@angular/material/core/overlay/scroll/scrollable.js:28:0 <- src/test.ts:85186:22)
	    at Wrapper_Scrollable.ngOnDestroy (/OverlayModule/Scrollable/wrapper.ngfactory.js:13:16)
	    at CompiledTemplate.proxyViewClass.View_MdSidenavContainer0.destroyInternal (/MdSidenavModule/MdSidenavContainer/component.ngfactory.js:66:24)
	    at CompiledTemplate.proxyViewClass.AppView.destroy (webpack:///~/@angular/core/src/linker/view.js:203:0 <- src/test.ts:81045:14)
	    at CompiledTemplate.proxyViewClass.DebugAppView.destroy (webpack:///~/@angular/core/src/linker/view.js:606:0 <- src/test.ts:81448:38)
	    at CompiledTemplate.proxyViewClass.View_AppComponent0.destroyInternal (/DynamicTestModule/AppComponent/component.ngfactory.js:107:19)
	    at CompiledTemplate.proxyViewClass.AppView.destroy (webpack:///~/@angular/core/src/linker/view.js:203:0 <- src/test.ts:81045:14)
	    at CompiledTemplate.proxyViewClass.DebugAppView.destroy (webpack:///~/@angular/core/src/linker/view.js:606:0 <- src/test.ts:81448:38)
	    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.destroyInternal (/DynamicTestModule/AppComponent/host.ngfactory.js:33:19)
	    at CompiledTemplate.proxyViewClass.AppView.destroy (webpack:///~/@angular/core/src/linker/view.js:203:0 <- src/test.ts:81045:14)
	    at CompiledTemplate.proxyViewClass.DebugAppView.destroy (webpack:///~/@angular/core/src/linker/view.js:606:0 <- src/test.ts:81448:38)
	    at CompiledTemplate.proxyViewClass.AppView.detachAndDestroy (webpack:///~/@angular/core/src/linker/view.js:187:0 <- src/test.ts:81029:14)
	    at ComponentRef_.destroy (webpack:///~/@angular/core/src/linker/component_factory.js:147:51 <- src/test.ts:39360:70)
	    at ComponentFixture.destroy (webpack:///~/@angular/core/bundles/core-testing.umd.js:263:0 <- src/test.ts:69117:35)
```

**Comment by kara** [comment]
@Sabartius Thanks for the additional info. It looks like the first two tests generated by the CLI do not call `fixture.detectChanges()`. This means that change detection isn't run, so the onInit hook will never fire properly to set up the subscription. In this case, the test should fail because it's not accurately simulating the lifecycle of the component. To fix your test, just call detectChanges after you create your component.

**Comment by valerymelou** [comment]
Sorry to bring this up but I've got a setup here where `fixture.detectChanges()` is called but I still got the error.

Here is my spec
```
import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';
import { DebugElement } from '@angular/core';
import { MaterialModule } from '@angular/material';

import { DashboardComponent } from './dashboard.component';

describe('DashboardComponent', () => {
  let component: DashboardComponent;
  let fixture: ComponentFixture<DashboardComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [MaterialModule],
      declarations: [DashboardComponent]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(DashboardComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

and the template
```
<md-card>
  <md-card-title>Dashboard</md-card-title>
</md-card>
```

**Comment by Sabartius** [comment]
@kara is this really the preferred way? I have around 200 Tests that worked with Beta1 that fail now after the upgrade to Beta2. I often use the TestBed and Injection to Test Component-Behavior without using the dom, so that i don't need to call `fixture.detectChanges()`, but now it would be always necessary to call it?

**Comment by jdenekat** [comment]
I got this error message to go away after I imported ComponentFixture from @angular/core/testing, which the cli did not include.  Then all my tests ran, including ones without the testbed for an isolated service test.  Prior to that, every single test failed whether it was using the service bed or not.

**Comment by divan** [comment]
I have the same error, none of the workarounds described above works for me. I have `ComponentFixture` imported and `fixture.detectChanges()` in the spec.ts included by `ng g component ..` generator.

**Comment by divan** [comment]
Here is a dirty workaround until this issue is resolved: 
In file `node_modules/@angular/material/core/overlay/scroll/scroll-dispatcher.js` change line 52 to
```
    ScrollDispatcher.prototype.deregister = function (scrollable) {
        if (this.scrollableReferences.get(scrollable) != null) {
            this.scrollableReferences.get(scrollable).unsubscribe();
        };
        this.scrollableReferences.delete(scrollable);
    };
```

At least it makes tests pass until the issue is being investigated.
