### ISSUE TITLE
Example app broken

### ISSUE THREAD

**Issue by prestonvanloon** [angular/material2#3621]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Clicking https://material.angular.io/guide/material2-app from https://material.angular.io/guide/getting-started should load the example app.

#### What is the current behavior?
```
TypeError: Cannot read property 'document' of undefined
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:28:9953)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at e.t.internalDetectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5542)
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:28:7809)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at t.detectChangesInNestedViews (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:57:780)
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:26:9934)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at e.t.internalDetectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5542)
    at e.detectChangesInternal (https://material.angular.io/main.187804ec05c88255b68e.bundle.js:26:8430)
    at e.t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:36:5749)
    at t.detectChanges (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:1008:1301)
    at https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:183:5180
    at Array.forEach (native)
    at e.tick (https://material.angular.io/vendor.cd86af5b77b0c0342f39.bundle.js:183:5147)
```

#### What are the steps to reproduce?
Go to: https://material.angular.io/guide/material2-app

#### What is the use-case or motivation for changing an existing behavior?
It's broken.

#### Which versions of Angular, Material, OS, browsers are affected?
All (probably). 

#### Is there anything else we should know?
No

**Comment by Chan4077** [comment]
See #3388.

**Comment by prestonvanloon** [comment]
Thanks @Chan4077 I'll go ahead and close this as duplicate of #3388
