### ISSUE TITLE
Menu e2e is failing

### ISSUE THREAD

**Issue by alexw10** [angular/material2#3838]
#### Bug, feature request, or proposal:
  There seems to be a bug pulling a fresh clone of latest material2.
  npm install
gulp e2e

Fails with:
Failures:
  1) menu should support multiple triggers opening the same menu
Message:
  Failed: unknown error: Element <div class="cdk-overlay-backdrop" style="pointer-events: none;"></div> is not clickable at point (512, 347). Other element would receive the click: <div class="cdk-overlay-backdrop cdk-overlay-transparent-backdrop cdk-overlay-backdrop-showing"></div>
  (Session info: chrome=56.0.2924.87)
(Driver info: chromedriver=2.28.455517 (2c6d2707d8ea850c862f04ac066724273981e88f),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 14 milliseconds
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_73'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.28.455517 (2c6d2707d8ea850c862f04ac066724273981e88f), userDataDir=/var/folders/l0/p6sn4c3d3tb8d23j6lnzq_94c2rv6m/T/.org.chromium.Chromium.xoe3iY}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=56.0.2924.87, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: e1685b753d95e9ae4038202c2bb9035b
Stack:
  WebDriverError: unknown error: Element <div class="cdk-overlay-backdrop" style="pointer-events: none;"></div> is not clickable at point (512, 347). Other element would receive the click: <div class="cdk-overlay-backdrop cdk-overlay-transparent-backdrop cdk-overlay-backdrop-showing"></div>
  (Session info: chrome=56.0.2924.87)
(Driver info: chromedriver=2.28.455517 (2c6d2707d8ea850c862f04ac066724273981e88f),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 14 milliseconds
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: , os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_73'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.28.455517 (2c6d2707d8ea850c862f04ac066724273981e88f), userDataDir=/var/folders/l0/p6sn4c3d3tb8d23j6lnzq_94c2rv6m/T/.org.chromium.Chromium.xoe3iY}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=56.0.2924.87, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: e1685b753d95e9ae4038202c2bb9035b
at Object.checkLegacyResponse (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:505:15)
at parseHttpResponse (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
at doSend.then.response (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:440:13)
at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebElement.click()
at thenableWebDriverProxy.schedule (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
at WebElement.schedule_ (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:1921:25)
at WebElement.click (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:2002:17)
at actionFn (/projects/material2/node_modules/protractor/lib/element.ts:94:34)
at Array.map (native)
at actionResults.getWebElements.then (/projects/material2/node_modules/protractor/lib/element.ts:484:67)
at ManagedPromise.invokeCallback_ (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1366:14)
at TaskQueue.execute_ (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
at TaskQueue.executeNext_ (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
at asyncRun (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2813:27)Error
at ElementArrayFinder.applyAction_ (/projects/material2/node_modules/protractor/lib/element.ts:482:23)
at ElementArrayFinder.(anonymous function).args [as click] (/projects/material2/node_modules/protractor/lib/element.ts:96:21)
at ElementFinder.(anonymous function).args [as click] (/projects/material2/node_modules/protractor/lib/element.ts:873:14)
at Object.<anonymous> (/projects/material2/e2e/components/menu/menu.e2e.ts:62:21)
at /projects/material2/node_modules/jasminewd2/index.js:110:25
at new ManagedPromise (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1067:7)
at ControlFlow.promise (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2396:12)
at schedulerExecute (/projects/material2/node_modules/jasminewd2/index.js:95:18)
at TaskQueue.execute_ (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
at TaskQueue.executeNext_ (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
From: Task: Run it("should support multiple triggers opening the same menu") in control flow
at Object.<anonymous> (/projects/material2/node_modules/jasminewd2/index.js:94:19)
at /projects/material2/node_modules/jasminewd2/index.js:64:48
at ControlFlow.emit (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/events.js:62:21)
at ControlFlow.shutdown_ (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2565:10)
at shutdownTask_.MicroTask (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2490:53)
at MicroTask.asyncRun (/projects/material2/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2619:9)
From asynchronous test:
  Error
at Suite.<anonymous> (/projects/material2/e2e/components/menu/menu.e2e.ts:48:3)
at Object.<anonymous> (/projects/material2/e2e/components/menu/menu.e2e.ts:7:1)
at Module._compile (module.js:571:32)
at Module.m._compile (/projects/material2/node_modules/ts-node/src/index.ts:395:23)
at Module._extensions..js (module.js:580:10)
at Object.require.extensions.(anonymous function) [as .ts] (/projects/material2/node_modules/ts-node/src/index.ts:398:12)

60 specs, 1 failure
Finished in 117.672 seconds

#### What is the expected behavior?
  All e2e tests should pass.

#### What is the current behavior?
  Menu e2e is failing

#### What are the steps to reproduce?

  Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
  Plunker template: https://goo.gl/DlHd6U
  clone material 2 repo
npm install
gulp e2e

#### Which versions of Angular, Material, OS, browsers are affected?
  Angular 4.0, Material latest, Mac, Chrome

**Comment by jelbourn** [comment]
May have been a temporary flake, everything seems to be passing now.

**Comment by dalelotts** [comment]
This happens consistency on my local machine. I will submit a PR shortly
