### ISSUE TITLE
md-select example is broken

### ISSUE THREAD

**Issue by diminutivesloop** [angular/material2#3929]
The md-select example on Plunker does not display any options when the select control is clicked. Additionally the following errors are printed to the console when it loads.

```
ERROR Error: Found the synthetic property @transformPlaceholder. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
    at checkNoSyntheticProp (unpkg.com/@angular/platform-browser/bundles/platform-browser.umd.js:2963)
    at DefaultDomRenderer2.setProperty (unpkg.com/@angular/platform-browser/bundles/platform-browser.umd.js:2931)
    at DebugRenderer2.setProperty (unpkg.com/@angular/core/bundles/core.umd.js:13269)
    at setElementProperty (unpkg.com/@angular/core/bundles/core.umd.js:9544)
    at checkAndUpdateElementValue (unpkg.com/@angular/core/bundles/core.umd.js:9463)
    at checkAndUpdateElementInline (unpkg.com/@angular/core/bundles/core.umd.js:9399)
    at checkAndUpdateNodeInline (unpkg.com/@angular/core/bundles/core.umd.js:12090)
    at checkAndUpdateNode (unpkg.com/@angular/core/bundles/core.umd.js:12065)
    at debugCheckAndUpdateNode (unpkg.com/@angular/core/bundles/core.umd.js:12694)
    at debugCheckRenderNodeFn (unpkg.com/@angular/core/bundles/core.umd.js:12673)
Unhandled Promise rejection: Found the synthetic property @transformPlaceholder. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application. ; Zone: <root> ; Task: Promise.then ; Value: Error: Found the synthetic property @transformPlaceholder. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
    at checkNoSyntheticProp (unpkg.com/@angular/platform-browser/bundles/platform-browser.umd.js:2963)
    at DefaultDomRenderer2.setProperty (unpkg.com/@angular/platform-browser/bundles/platform-browser.umd.js:2931)
    at DebugRenderer2.setProperty (unpkg.com/@angular/core/bundles/core.umd.js:13269)
    at setElementProperty (unpkg.com/@angular/core/bundles/core.umd.js:9544)
    at checkAndUpdateElementValue (unpkg.com/@angular/core/bundles/core.umd.js:9463)
    at checkAndUpdateElementInline (unpkg.com/@angular/core/bundles/core.umd.js:9399)
    at checkAndUpdateNodeInline (unpkg.com/@angular/core/bundles/core.umd.js:12090)
    at checkAndUpdateNode (unpkg.com/@angular/core/bundles/core.umd.js:12065)
    at debugCheckAndUpdateNode (unpkg.com/@angular/core/bundles/core.umd.js:12694)
    at debugCheckRenderNodeFn (unpkg.com/@angular/core/bundles/core.umd.js:12673) Error: Found the synthetic property @transformPlaceholder. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
    at checkNoSyntheticProp (https://unpkg.com/@angular/platform-browser/bundles/platform-browser.umd.js:2963:15)
    at DefaultDomRenderer2.setProperty (https://unpkg.com/@angular/platform-browser/bundles/platform-browser.umd.js:2931:9)
    at DebugRenderer2.setProperty (https://unpkg.com/@angular/core/bundles/core.umd.js:13269:23)
    at setElementProperty (https://unpkg.com/@angular/core/bundles/core.umd.js:9544:19)
    at checkAndUpdateElementValue (https://unpkg.com/@angular/core/bundles/core.umd.js:9463:13)
    at checkAndUpdateElementInline (https://unpkg.com/@angular/core/bundles/core.umd.js:9399:24)
    at checkAndUpdateNodeInline (https://unpkg.com/@angular/core/bundles/core.umd.js:12090:23)
    at checkAndUpdateNode (https://unpkg.com/@angular/core/bundles/core.umd.js:12065:16)
    at debugCheckAndUpdateNode (https://unpkg.com/@angular/core/bundles/core.umd.js:12694:59)
    at debugCheckRenderNodeFn (https://unpkg.com/@angular/core/bundles/core.umd.js:12673:13)
Error: Uncaught (in promise): Error: Found the synthetic property @transformPlaceholder. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
    at l (zone.min.js:1)
    at zone.min.js:1
    at e.invoke (zone.min.js:1)
    at n.run (zone.min.js:1)
    at zone.min.js:1
    at e.invokeTask (zone.min.js:1)
    at n.runTask (zone.min.js:1)
    at a (zone.min.js:1)
    at XMLHttpRequest.invoke (zone.min.js:1)
```

**Comment by donroyco** [comment]
What Plunker are you referring to, @diminutivesloop ?

**Comment by diminutivesloop** [comment]
The one accessible from this page: https://material.angular.io/components/component/select. I've forked my own copy here: https://plnkr.co/edit/CymzRFhKh4rtSqnReGpv?p=preview.

**Comment by willshowell** [comment]
Looks like the new @angular/animations packages need to be added to the plunker template 

https://github.com/angular/material.angular.io/blob/master/src/assets/plunker/systemjs.config.js

**Comment by tobi-or-not-tobi** [comment]
I had the same, I read the [getting started instructions](https://github.com/angular/material2/blob/master/guides/getting-started.md) again, and added the BrowserAnimationsModule. This seems to be added for angular 4 compatibility (see https://github.com/angular/material2/commit/cd55082a488e58a3f4948bba8e5d0a6771a57233). Problem solved.

**Comment by jelbourn** [comment]
All the plunkers on the docs site should be fixed now.
