### ISSUE TITLE
MdMenu - tests failing

### ISSUE THREAD

**Issue by RobJacobs** [angular/material2#5150]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
menu tests to complete

#### What is the current behavior?
menu.spec.ts is failing at line 82 and line 94

#### What are the steps to reproduce?
A fresh clone of the repo, then npm install, then gulp test:single-run.  Does not occur on a stale clone updated from master branch.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Win 10, chrome 59.0.3071.86, node 6.11.0, npm 3.10.10, karma 1.7.0

**Comment by jelbourn** [comment]
It's green on CI and passes for me locally. Potentially an issue w/ your environment.

**Comment by RobJacobs** [comment]
@jelbourn It only happens on a fresh clone.  I've tried on 2 different machines with the same results.  I've run into this situation before under #4654.

**Comment by willshowell** [comment]
I can corroborate this

**Comment by jelbourn** [comment]
Yep, I see it after wiping node_modules

**Comment by alexw10** [comment]
The reason this is happening is cause of the Angular 4.2.2 release.
Just tried this as well and the menu tests fail:
Chrome 59.0.3071 (Mac OS X 10.12.5) MdMenu should close the menu when a click occurs outside the menu FAILED
        Expected '
               Item 
               Disabled 
            ' to be ''.
            at Object.eval (src/lib/menu/menu.spec.ts:82:48 <- dist/packages/material/menu/menu.spec.js:59:53)
            at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
            at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:79:39)
            at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:390:32)
            at Zone.run (node_modules/zone.js/dist/zone.js:141:43)
            at Object.<anonymous> (node_modules/zone.js/dist/jasmine-patch.js:104:34)
            at eval (node_modules/@angular/core/bundles/core-testing.umd.js:127:17)
            at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
            at AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/async-test.js:49:39)
            at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:76:39)
            at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:390:32)
            at Zone.run (node_modules/zone.js/dist/zone.js:141:43)
            at AsyncTestZoneSpec.eval [as _finishCallback] (node_modules/@angular/core/bundles/core-testing.umd.js:122:25)
            at node_modules/zone.js/dist/async-test.js:38:31
            at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:424:31)
            at Zone.runTask (node_modules/zone.js/dist/zone.js:191:47)
            at ZoneTask.invoke (node_modules/zone.js/dist/zone.js:486:38)
            at timer (node_modules/zone.js/dist/zone.js:1540:29)
Chrome 59.0.3071 (Mac OS X 10.12.5) MdMenu should close the menu when pressing escape FAILED
        Expected '
               Item 
               Disabled 
            ' to be ''.
            at Object.eval (src/lib/menu/menu.spec.ts:94:48 <- dist/packages/material/menu/menu.spec.js:68:53)
            at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
            at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:79:39)
            at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:390:32)
            at Zone.run (node_modules/zone.js/dist/zone.js:141:43)
            at Object.<anonymous> (node_modules/zone.js/dist/jasmine-patch.js:104:34)
            at eval (node_modules/@angular/core/bundles/core-testing.umd.js:127:17)
            at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
            at AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/async-test.js:49:39)
            at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:76:39)
            at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:390:32)
            at Zone.run (node_modules/zone.js/dist/zone.js:141:43)
            at AsyncTestZoneSpec.eval [as _finishCallback] (node_modules/@angular/core/bundles/core-testing.umd.js:122:25)
            at node_modules/zone.js/dist/async-test.js:38:31
            at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:424:31)
            at Zone.runTask (node_modules/zone.js/dist/zone.js:191:47)
            at ZoneTask.invoke (node_modules/zone.js/dist/zone.js:486:38)
            at timer (node_modules/zone.js/dist/zone.js:1540:29)

Any ETA on this?

**Comment by alexw10** [comment]
I did a little more digging into this, it seems like both the tests are failing I am able to successfully do in the demo-app.

For example clicking outside of the menu does close it in the demo app.
As well as if I tab into the menu hit enter to open it so it is all keyboard focus'd, I am able to hit ESCAPE to close.

So demo app the two tests scenarios that are failing seem to work:
  it('should close the menu when a click occurs outside the menu', () => {
    const fixture = TestBed.createComponent(SimpleMenu);
    fixture.detectChanges();
    fixture.componentInstance.trigger.openMenu();

    const backdrop = <HTMLElement>overlayContainerElement.querySelector('.cdk-overlay-backdrop');
    backdrop.click();
    fixture.detectChanges();

    expect(overlayContainerElement.textContent).toBe('');
  });

  it('should close the menu when pressing escape', () => {
    const fixture = TestBed.createComponent(SimpleMenu);
    fixture.detectChanges();
    fixture.componentInstance.trigger.openMenu();

    const panel = overlayContainerElement.querySelector('.mat-menu-panel');
    dispatchKeyboardEvent(panel, 'keydown', ESCAPE);
    fixture.detectChanges();

    expect(overlayContainerElement.textContent).toBe('');
  });

Need to head out now though, might dig into it more tomorrow if you guys aren't able to get to it by then.

**Comment by willshowell** [comment]
For me, setting an exact dependency of Angular at 4.1.3 passes whereas 4.2.0-rc.0 and higher fail

**Comment by alexw10** [comment]
yup exactly @willshowell it has to do with the latest Angular release in someway.

**Comment by jelbourn** [comment]
Fixed in #6483
