### ISSUE TITLE
Problem with rendering the universal application with angular/material

### ISSUE THREAD

**Issue by httpsOmkar** [angular/material2#5324]
#### Bug
Error while compiling the application as the universal application.

#### What is the expected behavior?
It should serve universal application without getting any error.

#### What is the current behavior?
```
import * as i0 from '@angular/core';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/ok/angular-seo/node_modules/ts-node/src/index.ts:400:14)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular-material 2.0.0-beta.7
@angular 4.2.3
typescript 2.2.2

#### Is there anything else we should know?
I'm trying to implement the universal application but problem is when I import the MdButtonModule in this application it generate the above error. How to fix this error.

**Comment by glemiere** [comment]
Related to : https://github.com/angular/material2/issues/308

**Comment by jelbourn** [comment]
Tracked on #308

**Comment by glemiere** [comment]
Any news here ?
