### ISSUE TITLE
Cannot run demo-app

### ISSUE THREAD

**Issue by amitport** [angular/material2#6212]
#### Bug, feature request, or proposal:
development bug

#### What is the expected behavior?
npm i && npm run demo-app should start the demo app

#### What is the current behavior?
```
Error: Cannot find module 'tsickle'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module._load ([.....]\material2\node_modules\tsconfig-paths\lib\register.js:26:31)
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material2  hash 8a23157dc3f3be53afa01fe5af5bf214a6c13a2e

#### Is there anything else we should know?
windows 7
npm 5.0.3
Probably side-effect of https://github.com/angular/material2/issues/6211

**Comment by DevVersion** [comment]
This happend a few times to me as well. It looks like the dependencies are not installed properly. Do you think you can try re-installing the node_modules again?

**Comment by amitport** [comment]
a little better on latest (https://github.com/angular/material2/commit/72360e2b11a9b13966da821893a32bc20422848c). Now I'm getting

```
[16:07:26] 'cdk:build:esm' errored after 1.42 s
[16:07:26] TypeError: Cannot read property 'toString' of null
    at C:\Users\amportnoy\ws\temp\material2\tools\package-tools\secondary-entry-points.ts:42:13
    at Array.forEach (<anonymous>)
    at Object.getSecondaryEntryPointsForPackage (C:\Users\amportnoy\ws\temp\material2\tools\package-tools\secondary-entry-points.ts:38:14)
    at BuildPackage.get [as secondaryEntryPoints] (C:\Users\amportnoy\ws\temp\material2\tools\package-tools\build-package.ts:36:36)
    at BuildPackage.<anonymous> (C:\Users\amportnoy\ws\temp\material2\tools\package-tools\build-package.ts:59:34)
    at step (C:\Users\amportnoy\ws\temp\material2\tools\package-tools\build-package.ts:32:23)
    at Object.next (C:\Users\amportnoy\ws\temp\material2\tools\package-tools\build-package.ts:13:53)
    at fulfilled (C:\Users\amportnoy\ws\temp\material2\tools\package-tools\build-package.ts:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by benb7760** [comment]
@amitport Try using git bash as per [comment](https://github.com/angular/material2/issues/6211#issuecomment-321091100)

**Comment by jelbourn** [comment]
Currently our dev build requires a unix/linux environment (or something like git bash)

**Comment by ipassynk** [comment]
Yes, the problem is gone on windows when git bash is used. Thanks. May be the build should notify windows the user on start about it to avoid frustration.

**Comment by benb7760** [comment]
@ipassynk A proper fix has since been merged and will be included in the next release #6652

**Comment by MaximeAnsquer** [comment]
I still get 

`TypeError: Cannot read property 'toString' of null
    at D:\devhome\working_directory\material2\tools\package-tools\secondary-entr                                                                                                                                                                                               y-points.ts:39:13`

on Windows using Git Bash

**Comment by amitport** [comment]
Fixed for me on master (https://github.com/angular/material2/commit/f375f92581b6318219cc225aeafc97124a840b26). Windows *without* git bash.
