### ISSUE TITLE
TypeError: this._getHostElement(...).focus is not a function

### ISSUE THREAD

**Issue by GuskiS** [angular/material2#6292]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Using [this guide](https://github.com/angular/angular-cli/wiki/stories-universal-rendering) I would like to be able render app without errors.

#### What is the current behavior?
Currently I'm recieving error:
```
ERROR { Error: Uncaught (in promise): TypeError: this._getHostElement(...).focus is not a function
TypeError: this._getHostElement(...).focus is not a function
    at MdOption.focus (home_path/node_modules/@angular/material/bundles/material.umd.js:1638:32)
    at FocusKeyManager.setActiveItem (home_path/node_modules/@angular/material/bundles/material.umd.js:6787:29)
    at MdSelect._selectValue (home_path/node_modules/@angular/material/bundles/material.umd.js:7454:30)
    at MdSelect._setSelectionByValue (home_path/node_modules/@angular/material/bundles/material.umd.js:7431:18)
    at MdSelect.writeValue (home_path/node_modules/@angular/material/bundles/material.umd.js:7237:18)
    at home_path/node_modules/@angular/forms/bundles/forms.umd.js:1810:29
    at home_path/node_modules/@angular/forms/bundles/forms.umd.js:2996:65
    at Array.forEach (native)
    at FormControl.setValue (home_path/node_modules/@angular/forms/bundles/forms.umd.js:2996:28)
    at home_path/node_modules/@angular/forms/bundles/forms.umd.js:4398:60
    at resolvePromise (home_path/node_modules/zone.js/dist/zone-node.js:783:31)
    at home_path/node_modules/zone.js/dist/zone-node.js:834:17
    at ZoneDelegate.invokeTask (home_path/node_modules/zone.js/dist/zone-node.js:424:31)
    at Object.onInvokeTask (home_path/node_modules/@angular/core/bundles/core.umd.js:3913:33)
    at ZoneDelegate.invokeTask (home_path/node_modules/zone.js/dist/zone-node.js:423:36)
    at Zone.runTask (home_path/node_modules/zone.js/dist/zone-node.js:191:47)
    at drainMicroTaskQueue (home_path/node_modules/zone.js/dist/zone-node.js:595:35)
    at ZoneTask.invokeTask (home_path/node_modules/zone.js/dist/zone-node.js:502:21)
    at ZoneTask.invoke (home_path/node_modules/zone.js/dist/zone-node.js:487:48)
    at data.args.(anonymous function) (home_path/node_modules/zone.js/dist/zone-node.js:1063:25)
```
However, I'm still able to produce out html.
#### What are the steps to reproduce?
I have these [modules](https://gist.github.com/GuskiS/61285100e06b9226f0412a5e8ebbac75)
Looking at the error message it seems that select is causing this, so here is my select:
Example code:
```
...
  buttons = ["left", "middle", "right"]
  button = this.buttons[0]
...
  <md-select (change)="change()" [(ngModel)]="button">
    <md-option *ngFor="let mb of buttons" [value]="mb">{{ mb | uppercase }}</md-option>
  </md-select>
...
```
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular - 4.3.3
Material - 2.0.0-beta.8
OS - Ubuntu 16.10
TypeScript - 2.4.2

#### Is there anything else we should know?
For some reason `Current document does not have a doctype. This may cause some Angular Material components not to behave as expected.` is outputed, however, I do have `doctype`.

**Comment by joaogarin** [comment]
I am experiencing the same issue running app in universal. any idea for a workardound?

**Comment by crisbeto** [comment]
This should be fixed in the next release by https://github.com/angular/material2/commit/2388d91642593fbbed423035a459e7c92520eb37.

**Comment by GuskiS** [comment]
Great. When is next release planned?

**Comment by halben** [comment]
Any update on why 

> For some reason Current document does not have a doctype. This may cause some Angular Material components not to behave as expected. is outputed, however, I do have doctype.

is being outputted?

**Comment by crisbeto** [comment]
It means that it might be incorrect. The way we verify the doctype is by checking the `document.doctype`.

**Comment by GuskiS** [comment]
I have it like this - https://github.com/GuskiS/mobile-mouse/blob/master/app/angular/mobile/index.html#L1
Default from CLI, I think.

**Comment by halben** [comment]
@crisbeto so that means it will complain every time on ServerSide Rendering?

**Comment by crisbeto** [comment]
It won't do anything if it doesn't have a `document`.

**Comment by neilhem** [comment]
Angular Material 2.0.0-beta.10 has been released which still has this error on server side

**Comment by ocombe** [comment]
I confirm that I have this error as well when material is used without the dom (for node tests)

**Comment by m98** [comment]
I'm experiencing the same error.

I'm getting this for server-side rendering...
