### ISSUE TITLE
Can't build and run demo-app on windows

### ISSUE THREAD

**Issue by hasan-assi** [angular/material2#7123]
#### Bug

> material2-srcs@2.0.0-beta.11 demo-app C:\github\material2
> gulp serve:devapp

[15:31:37] Using gulpfile C:\github\material2\gulpfile.js
[15:31:37] Starting 'build:devapp'...
[15:31:37] Starting 'material-moment-adapter:clean-build'...
[15:31:37] Starting 'clean'...
[15:31:37] Finished 'clean' after 14 ms
[15:31:37] Starting 'material-moment-adapter:build'...
[15:31:37] Starting 'material:build'...
[15:31:37] Starting 'cdk:build'...
[15:31:37] Starting 'cdk:build:esm'...
[15:31:37] Starting 'cdk:assets:scss'...
[15:31:37] Starting 'cdk:assets:copy-styles'...
[15:31:37] Starting 'cdk:assets:html'...
Error: spawn ./node_modules/.bin/ngc ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

#### What is the expected behavior?

run demo-app locally on windows without issues

#### What is the current behavior?
build failed

#### What are the steps to reproduce?
npm run demo-app 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/material 'master' / the latest. Windows 10

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/material2/pull/7120.
