### ISSUE TITLE
All Plunker examples are broken

### ISSUE THREAD

**Issue by danmana** [angular/material2#7573]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Plunker examples (from https://material.angular.io/components) load

#### What is the current behavior?
Plunker is stuck at "Loading Material Docs example"

Stack trace:
```
Error: (SystemJS) Unexpected value 'undefined' exported by the module 'PlunkerMaterialModule'
	Error: Unexpected value 'undefined' exported by the module 'PlunkerMaterialModule'
	    at d (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:10303)
	    at syntaxError (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:1729:34)
	    at eval (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:15596:40)
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver.getNgModuleMetadata (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:15594:49)
	    at CompileMetadataResolver.getNgModuleSummary (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:15507:52)
	    at eval (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:15580:72)
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver.getNgModuleMetadata (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:15565:49)
	    at JitCompiler._loadModules (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:27000:70)
	    at JitCompiler._compileModuleAndComponents (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:26973:36)
	    at JitCompiler.compileModuleAsync (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:26902:37)
	    at PlatformRef_._bootstrapModuleWithZone (https://unpkg.com/@angular/core/bundles/core.umd.js:4568:25)
	    at PlatformRef_.bootstrapModule (https://unpkg.com/@angular/core/bundles/core.umd.js:4554:21)
	    at execute (http://run.plnkr.co/z36x3ZY7m8N6588A/main.ts!transpiled:108:65)
	Error loading http://run.plnkr.co/z36x3ZY7m8N6588A/main.ts
	    at d (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:10303)
	    at syntaxError (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:1729:34)
	    at eval (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:15596:40)
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver.getNgModuleMetadata (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:15594:49)
	    at CompileMetadataResolver.getNgModuleSummary (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:15507:52)
	    at eval (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:15580:72)
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver.getNgModuleMetadata (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:15565:49)
	    at JitCompiler._loadModules (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:27000:70)
	    at JitCompiler._compileModuleAndComponents (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:26973:36)
	    at JitCompiler.compileModuleAsync (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:26902:37)
	    at PlatformRef_._bootstrapModuleWithZone (https://unpkg.com/@angular/core/bundles/core.umd.js:4568:25)
	    at PlatformRef_.bootstrapModule (https://unpkg.com/@angular/core/bundles/core.umd.js:4554:21)
	    at execute (http://run.plnkr.co/z36x3ZY7m8N6588A/main.ts!transpiled:108:65)
	Error loading http://run.plnkr.co/z36x3ZY7m8N6588A/main.ts
e.invoke @ zone.min.js:1
```

#### What are the steps to reproduce?
This is a clone of the button plunker from https://material.angular.io/components/button/overview
http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview

All plunker examples linked from https://material.angular.io/components fail the same way

#### Is there anything else we should know?
Browser Chrome - fails (but in incognito it works)
Firefox - fails with an additional error
```
xhr construction TypeError: window.XDomainRequest is not a constructor
Stack trace:
oxhbjs</t.ajax/a<@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:13:22012
oxhbjs</t.ajax@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:13:21857
n/B.load@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:12:12309
i/v</</<@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:13:10892
n@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:11:3290
i/v</<@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:13:9802
i/v<@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:13:9670
oxhbjs</t._map@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:11:27992
i@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:13:9642
g@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:13:13576
t@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:13:9491
c@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:11:8694
oxhbjs</t.fetchBids/</<@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:11:9629
n@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:11:3290
oxhbjs</t.fetchBids/<@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:11:9399
oxhbjs</t._each@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:11:27743
oxhbjs</t.fetchBids@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:11:8192
p/<@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:11:31479
n@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:11:3290
p@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:11:31430
l@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:11:30197
u@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:11:29813
c@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:12:25003
d/<@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:13:26424
n@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:11:3290
d@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:13:26364
n@https://freestar-d.openx.net/w/1.0/jstag?nc=15184186-Freestar_RON:13:26511
@https://pub.freestar.io/plnkr/pubfig.min.js:1:4179
fm.prototype.push@https://securepubads.g.doubleclick.net/gpt/pubads_impl_153.js:1:62754
_.O/<@https://securepubads.g.doubleclick.net/gpt/pubads_impl_153.js:1:61674
gm@https://securepubads.g.doubleclick.net/gpt/pubads_impl_153.js:1:63114
_.O/<@https://securepubads.g.doubleclick.net/gpt/pubads_impl_153.js:1:61674
vt@https://securepubads.g.doubleclick.net/gpt/pubads_impl_153.js:1:187751
@https://securepubads.g.doubleclick.net/gpt/pubads_impl_153.js:1:188519
@https://securepubads.g.doubleclick.net/gpt/pubads_impl_153.js:1:2
  jstag:13:22655
	
```

**Comment by danmana** [comment]
Seems related to #5285 and #5245

**Comment by bboehm86** [comment]
It's just that the module names (from `Md...Module` to `Mat...Module` in the `main.ts`) and the selectors (from `md...` to `mat...`) are not updated yet.

**Comment by kara** [comment]
This should be fixed (you may have to clear your cache)

**Comment by RoestVrijStaal** [comment]
> This should be fixed (you may have to clear your cache)

No, it isn't. 

No matter how hard I clean my cache or try to do it in Incognito Mode :expressionless:

**Comment by vinita1990** [comment]
for Angular 2 examples it is giving this error:

"xhr construction TypeError: window.XDomainRequest is not a constructor"
