### ISSUE TITLE
MdButtonModule is not a module

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/material2#7613]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
no bug

#### What is the current behavior?
after upgrading to `beta.12` I'm getting this error in both `ng-build --prod` and `ng-serve`:
```
ERROR in ./src/polyfills.ts
Module build failed: Error: TypeScript compilation failed.
    at plugin.done.then (C:\Development\Dochazka\src\Dochazka\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\loader.js:464:27)
 @ multi ./src/polyfills.ts
ERROR in ./src/main.ts
Module build failed: Error: TypeScript compilation failed.
    at plugin.done.then (C:\Development\Dochazka\src\Dochazka\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\loader.js:464:27)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ multi ./src/main.ts
ERROR in Error: Unexpected value 'MdButtonModule in C:/Development/Dochazka/src/Dochazka/node_modules/@angular/material/material.d.ts' imported by the module 'MaterialModule in C:/Development/Dochazka/src/Dochazka/src/app/shared/material.module.ts'. Please add a @NgModule annotation.
    at Error (native)
    at syntaxError (C:\Development\Dochazka\src\Dochazka\node_modules\@angular\compiler\bundles\compiler.umd.js:503:34)
    at C:\Development\Dochazka\src\Dochazka\node_modules\@angular\compiler\bundles\compiler.umd.js:15110:44
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Development\Dochazka\src\Dochazka\node_modules\@angular\compiler\bundles\compiler.umd.js:15093:49)
    at CompileMetadataResolver.getNgModuleSummary (C:\Development\Dochazka\src\Dochazka\node_modules\@angular\compiler\bundles\compiler.umd.js:15020:52)
    at C:\Development\Dochazka\src\Dochazka\node_modules\@angular\compiler\bundles\compiler.umd.js:15108:72
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Development\Dochazka\src\Dochazka\node_modules\@angular\compiler\bundles\compiler.umd.js:15093:49)
    at C:\Development\Dochazka\src\Dochazka\node_modules\@angular\compiler\bundles\compiler.umd.js:29850:70
    at Array.forEach (native)
    at analyzeFile (C:\Development\Dochazka\src\Dochazka\node_modules\@angular\compiler\bundles\compiler.umd.js:29829:53)
    at AotCompiler._analyzeFile (C:\Development\Dochazka\src\Dochazka\node_modules\@angular\compiler\bundles\compiler.umd.js:29123:17)
    at AotCompiler.findGeneratedFileNames (C:\Development\Dochazka\src\Dochazka\node_modules\@angular\compiler\bundles\compiler.umd.js:29139:42)
    at Object.findGeneratedFileNames (C:\Development\Dochazka\src\Dochazka\node_modules\@angular\compiler-cli\src\transformers\program.js:376:82)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getSourceFile (C:\Development\Dochazka\src\Dochazka\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:328:55)
```
All my npm packages are correctly installed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
windows 10

```
"dependencies": {
    "@angular/animations": "5.0.0-rc.1",
    "@angular/common": "5.0.0-rc.1",
    "@angular/compiler": "5.0.0-rc.1",
    "@angular/core": "5.0.0-rc.1",
    "@angular/forms": "5.0.0-rc.1",
    "@angular/http": "5.0.0-rc.1",
    "@angular/platform-browser": "5.0.0-rc.1",
    "@angular/platform-browser-dynamic": "5.0.0-rc.1",
    "@angular/router": "5.0.0-rc.1",
    "@angular/flex-layout": "git+https://github.com/angular/flex-layout-builds.git",
    "@angular/material": "2.0.0-beta.12",
    "@angular/cdk": "2.0.0-beta.12",
    "core-js": "2.5.1",
    "rxjs": "5.4.3",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@types/node": "*",
    "@angular/cli": "1.5.0-beta.4",
    "@angularclass/hmr": "2.1.3",
    "@angular/compiler-cli": "5.0.0-rc.1",
    "@angular/service-worker": "1.0.0-beta.16",
    "codelyzer": "3.2.0",
    "node-sass": "4.5.3",
    "ts-node": "3.3.0",
    "tslint": "5.7.0",
    "typescript": "2.5.3",
    "webpack-bundle-analyzer": "2.9.0"
  }
```

#### Is there anything else we should know?
this is my material module:
```
import { NgModule } from '@angular/core';
import { MATERIAL_COMPATIBILITY_MODE, MdButtonModule, MdCardModule, MdIconModule, MdInputModule, MdListModule, MdMenuModule, MdProgressSpinnerModule, MdSelectModule, MdSidenavModule, MdSlideToggleModule, MdSnackBarModule, MdTabsModule, MdToolbarModule } from '@angular/material';

@NgModule({
    imports: [
        MdButtonModule,
        MdCardModule,
        MdIconModule,
        MdInputModule,
        MdListModule,
        MdMenuModule,
        MdProgressSpinnerModule,
        MdSelectModule,
        MdSidenavModule,
        MdSlideToggleModule,
        MdSnackBarModule,
        MdTabsModule,
        MdToolbarModule
    ],
    declarations: [],
    exports: [
        MdButtonModule,
        MdCardModule,
        MdIconModule,
        MdInputModule,
        MdListModule,
        MdMenuModule,
        MdProgressSpinnerModule,
        MdSelectModule,
        MdSidenavModule,
        MdSlideToggleModule,
        MdSnackBarModule,
        MdTabsModule,
        MdToolbarModule
    ],
    providers: [
        { provide: MATERIAL_COMPATIBILITY_MODE, useValue: true }
    ]
})
export class MaterialModule { }
```

**Comment by CraigAOliver** [comment]
I assume your issue relates to the replacement of "md" with "mat".
It was outlined in the beta 11 release notes as below, probably could have been explicitly mentioned in 12 again as a breaking change.

> Deprecation of "md" prefix.
> 
> In earlier betas, we've had a compatibility mode that allowed people to use either "md" or "mat"
> as the selector for Angular Material components. This was created so that these components could
> live side-by-side with AngularJS Material without CSS from
> the two libraries colliding.
> 
> For beta.11, we've made the decision to deprecate the "md" prefix completely and use "mat" moving
> forward. This affects all class names, properties, inputs, outputs, and selectors (CSS classes were
> changed back in February). The "md" prefixes will be removed in the next beta release.
> 
> You can automatically update your projects with the angular-material-prefix-updater tool.
> Check out the tool's page for instructions on how to run.

**Comment by GeorgeKnap** [comment]
Right! The modules are now renamed as well.
Thanks.
