### ISSUE TITLE
Beta12 Demo-App

### ISSUE THREAD

**Issue by Paitum** [angular/material2#7647]
#### Bug, feature request, or proposal:
Bug-- but I'd bet $1 it's me.

#### What is the expected behavior?
That the Demo App would start.

#### What is the current behavior?
I get the following build failure:
```
C:\Dev\git\material2>npm run demo-app

> material2-srcs@2.0.0-beta.12 demo-app C:\Dev\git\material2
> gulp serve:devapp


C:\Dev\git\material2\node_modules\ts-node\src\index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ? Unable to compile TypeScript
tools\dgeni\common\sort-members.ts (19,25): Argument of type 'CategorizedMemberDoc' is not assignabl
e to parameter of type 'PropertyMemberDoc'.
  Type 'CategorizedMethodMemberDoc' is not assignable to type 'PropertyMemberDoc'.
    Property 'getAccessor' is missing in type 'CategorizedMethodMemberDoc'. (2345)
tools\dgeni\common\sort-members.ts (19,52): Argument of type 'CategorizedMemberDoc' is not assignabl
e to parameter of type 'PropertyMemberDoc'.
  Type 'CategorizedMethodMemberDoc' is not assignable to type 'PropertyMemberDoc'. (2345)
tools\dgeni\common\sort-members.ts (20,24): Argument of type 'CategorizedMemberDoc' is not assignabl
e to parameter of type 'PropertyMemberDoc'.
  Type 'CategorizedMethodMemberDoc' is not assignable to type 'PropertyMemberDoc'. (2345)
tools\dgeni\common\sort-members.ts (20,51): Argument of type 'CategorizedMemberDoc' is not assignabl
e to parameter of type 'PropertyMemberDoc'.
  Type 'CategorizedMethodMemberDoc' is not assignable to type 'PropertyMemberDoc'. (2345)
tools\dgeni\common\sort-members.ts (20,79): Argument of type 'CategorizedMemberDoc' is not assignabl
e to parameter of type 'PropertyMemberDoc'.
  Type 'CategorizedMethodMemberDoc' is not assignable to type 'PropertyMemberDoc'. (2345)
tools\dgeni\common\sort-members.ts (24,25): Argument of type 'CategorizedMemberDoc' is not assignabl
e to parameter of type 'PropertyMemberDoc'.
  Type 'CategorizedMethodMemberDoc' is not assignable to type 'PropertyMemberDoc'. (2345)
tools\dgeni\common\sort-members.ts (24,52): Argument of type 'CategorizedMemberDoc' is not assignabl
e to parameter of type 'PropertyMemberDoc'.
  Type 'CategorizedMethodMemberDoc' is not assignable to type 'PropertyMemberDoc'. (2345)
tools\dgeni\common\sort-members.ts (25,24): Argument of type 'CategorizedMemberDoc' is not assignabl
e to parameter of type 'PropertyMemberDoc'.
  Type 'CategorizedMethodMemberDoc' is not assignable to type 'PropertyMemberDoc'. (2345)
tools\dgeni\common\sort-members.ts (25,51): Argument of type 'CategorizedMemberDoc' is not assignabl
e to parameter of type 'PropertyMemberDoc'.
  Type 'CategorizedMethodMemberDoc' is not assignable to type 'PropertyMemberDoc'. (2345)
tools\dgeni\common\sort-members.ts (25,79): Argument of type 'CategorizedMemberDoc' is not assignabl
e to parameter of type 'PropertyMemberDoc'.
  Type 'CategorizedMethodMemberDoc' is not assignable to type 'PropertyMemberDoc'. (2345)
    at getOutput (C:\Dev\git\material2\node_modules\ts-node\src\index.ts:307:15)
    at C:\Dev\git\material2\node_modules\ts-node\src\index.ts:336:16
    at Object.compile (C:\Dev\git\material2\node_modules\ts-node\src\index.ts:498:11)
    at Module.m._compile (C:\Dev\git\material2\node_modules\ts-node\src\index.ts:392:43)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Dev\git\material2\node_modules\ts
-node\src\index.ts:395:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xbblypa\\AppData\\Roaming\\npm\\node
_modules\\npm\\bin\\npm-cli.js" "run" "demo-app"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! material2-srcs@2.0.0-beta.12 demo-app: `gulp serve:devapp`
npm ERR! Exit status 1
```

#### What are the steps to reproduce?
```
git clone https://github.com/angular/material2.git
cd material2
npm install
npm run demo-app 
```

#### What is the use-case or motivation for changing an existing behavior?
To try out Beta12.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.4.4
Material: 2.0.0-beta.12 commit 9fadf12c2941b739aa87e6d741b79dabc919dc61
NODE/NPM: 6.11.3/3.10.8
TSC: 2.4.2

#### Is there anything else we should know?
- I tried both master and 2.0.0-beta.12.
- beta11 works fine
- I am in a corporate environment. Which means my requests are proxies including npm. This could be something wrong with my environment.

**Comment by DevVersion** [comment]
This is due to a update of Dgeni-packages. Will be fixed as part of #7659

**Comment by Paitum** [comment]
Just curious, as I am new to interfacing with this repository: Is the problem I reported affecting everybody attempting to use master or beta12, or is there some kind of work-around that people are using? If there is no work-around, then how did this even make it out past CI? How are angular material developers able to work if the build system is failing?

(Again, I am asking because I feel I am missing something. I understand and respect that you are in beta, and that provides leeway.)

Thanks.

**Comment by andrewseguin** [comment]
Maybe Paul can give more info but I didn't personally run into this issue on my apps. Closing since the PR has been merged
