### ISSUE TITLE
Plunker templates crashes with 404 on https://raw.githubusercontent.com/angular/cdk-builds/master/bundles/cdk.umd.js/layout

### ISSUE THREAD

**Issue by eryi** [angular/material2#7676]
URL in readme.md  
http://plnkr.co/edit/LSgU9X5sYVhx4bc3LBWm?p=preview

URL in issue template  
https://goo.gl/DlHd6U  
redirects to http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=info  

Crash message  
````
Error: (SystemJS) XHR error (404 Not Found) loading https://rawgit.com/angular/cdk-builds/master/bundles/cdk.umd.js/layout
	Error: XHR error (404 Not Found) loading https://rawgit.com/angular/cdk-builds/master/bundles/cdk.umd.js/layout
	    at new d (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:10303)
	    at XMLHttpRequest.t [as _onreadystatechange] (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:730)
	    at e.invokeTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:15723)
	    at n.runTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:13076)
	    at XMLHttpRequest.invoke (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:16836)
	Error loading https://rawgit.com/angular/cdk-builds/master/bundles/cdk.umd.js/layout as "@angular/cdk/layout" from https://rawgit.com/angular/material2-builds/master/bundles/material.umd.js
	    at new d (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:10303)
	    at XMLHttpRequest.t [as _onreadystatechange] (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:730)
	    at e.invokeTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:15723)
	    at n.runTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:13076)
	    at XMLHttpRequest.invoke (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:16836)
	Error loading https://rawgit.com/angular/cdk-builds/master/bundles/cdk.umd.js/layout as "@angular/cdk/layout" from https://rawgit.com/angular/material2-builds/master/bundles/material.umd.js
````

**Comment by josephperrott** [comment]
@DevVersion Can you update your [plunker](http://plnkr.co/edit/o077B6uEiiIgkC0S06dd?p=preview) to have the `systemjs.config.js` file include the mapping for `layout`?

I will update the readme plunker link to also point to your plunker.

**Comment by josephperrott** [comment]
Closing as plunker has been updated.
