### ISSUE TITLE
Plunker template broken

### ISSUE THREAD

**Issue by victorblq** [angular/material2#7822]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
The plunker template loads

#### What is the current behavior?
The plunker template not loading

#### What are the steps to reproduce?
http://plnkr.co/edit/OlfIph?p=preview

#### Error
```
GET https://unpkg.com/@angular/cdk@2.0.0-beta.12/bundles/cdk.umd.js/accordion 404 ()
zone.min.js:1 Error: (SystemJS) XHR error (404) loading https://unpkg.com/@angular/cdk/bundles/cdk.umd.js/accordion
	Error: XHR error (404) loading https://unpkg.com/@angular/cdk/bundles/cdk.umd.js/accordion
	    at new d (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:10303)
	    at XMLHttpRequest.t [as _onreadystatechange] (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:730)
	    at e.invokeTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:15723)
	    at n.runTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:13076)
	    at XMLHttpRequest.invoke (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:16836)
	Error loading https://unpkg.com/@angular/cdk/bundles/cdk.umd.js/accordion as "@angular/cdk/accordion" from https://rawgit.com/angular/material2-builds/master/bundles/material.umd.js
	    at new d (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:10303)
	    at XMLHttpRequest.t [as _onreadystatechange] (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:730)
	    at e.invokeTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:15723)
	    at n.runTask (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:13076)
	    at XMLHttpRequest.invoke (https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.7.2/zone.min.js:1:16836)
	Error loading https://unpkg.com/@angular/cdk/bundles/cdk.umd.js/accordion as "@angular/cdk/accordion" from https://rawgit.com/angular/material2-builds/master/bundles/material.umd.js
e.invoke @ zone.min.js:1
n.run @ zone.min.js:1
(anonymous) @ zone.min.js:1
e.invokeTask @ zone.min.js:1
n.runTask @ zone.min.js:1
a @ zone.min.js:1
invoke @ zone.min.js:1
XMLHttpRequest.send (async)
n @ zone.min.js:1
e.scheduleTask @ zone.min.js:1
n.scheduleMacroTask @ zone.min.js:1
(anonymous) @ zone.min.js:1
send @ VM1758:3
W @ system.src.js:1043
(anonymous) @ system.src.js:1779
e @ zone.min.js:1
(anonymous) @ system.src.js:1778
(anonymous) @ system.src.js:2803
(anonymous) @ system.src.js:3381
(anonymous) @ system.src.js:3713
(anonymous) @ system.src.js:4105
(anonymous) @ system.src.js:4570
(anonymous) @ system.src.js:4839
(anonymous) @ system.src.js:408
e.invoke @ zone.min.js:1
n.run @ zone.min.js:1
(anonymous) @ zone.min.js:1
e.invokeTask @ zone.min.js:1
n.runTask @ zone.min.js:1
a @ zone.min.js:1
invoke @ zone.min.js:1
XMLHttpRequest.send (async)
n @ zone.min.js:1
e.scheduleTask @ zone.min.js:1
n.scheduleMacroTask @ zone.min.js:1
(anonymous) @ zone.min.js:1
send @ VM1758:3
W @ system.src.js:1043
(anonymous) @ system.src.js:1779
e @ zone.min.js:1
(anonymous) @ system.src.js:1778
(anonymous) @ system.src.js:2803
(anonymous) @ system.src.js:3381
(anonymous) @ system.src.js:3713
(anonymous) @ system.src.js:4105
(anonymous) @ system.src.js:4570
(anonymous) @ system.src.js:4839
(anonymous) @ system.src.js:408
e.invoke @ zone.min.js:1
n.run @ zone.min.js:1
(anonymous) @ zone.min.js:1
e.invokeTask @ zone.min.js:1
n.runTask @ zone.min.js:1
a @ zone.min.js:1
invoke @ zone.min.js:1
XMLHttpRequest.send (async)
n @ zone.min.js:1
e.scheduleTask @ zone.min.js:1
n.scheduleMacroTask @ zone.min.js:1
(anonymous) @ zone.min.js:1
send @ VM1758:3
W @ system.src.js:1043
(anonymous) @ system.src.js:1779
e @ zone.min.js:1
(anonymous) @ system.src.js:1778
(anonymous) @ system.src.js:2803
(anonymous) @ system.src.js:3381
(anonymous) @ system.src.js:3713
(anonymous) @ system.src.js:4105
(anonymous) @ system.src.js:4570
(anonymous) @ system.src.js:4839
(anonymous) @ system.src.js:408
e.invoke @ zone.min.js:1
n.run @ zone.min.js:1
(anonymous) @ zone.min.js:1
e.invokeTask @ zone.min.js:1
n.runTask @ zone.min.js:1
a @ zone.min.js:1
Promise resolved (async)
n @ zone.min.js:1
r @ zone.min.js:1
e.scheduleTask @ zone.min.js:1
n.scheduleMicroTask @ zone.min.js:1
p @ zone.min.js:1
e.then @ zone.min.js:1
(anonymous) @ system.src.js:4797
import @ system.src.js:830
(anonymous) @ system.src.js:1802
(anonymous) @ (index):20
unpkg.com/@angular/cdk@2.0.0-beta.12/bundles/cdk.umd.js/layout:1 GET https://unpkg.com/@angular/cdk@2.0.0-beta.12/bundles/cdk.umd.js/layout 404 ()```

**Comment by willshowell** [comment]
cc @DevVersion

**Comment by DevVersion** [comment]
Fixed

**Comment by GregKass** [comment]
@DevVersion Could you provide a brief description of the fix so that others of us that experience the same problem have an idea of where to begin fixing it?

**Comment by willshowell** [comment]
@GregKass typically when they are broken, the fix is to simply add new cdk packages to the systemjs config. You can identify which package is missing by looking at the console. Then just copy one of the existing package declarations and replace the name.

**Comment by victorblq** [comment]
I try to pass my plunker to you, but it stop working again, its giving me 404 error when try to get https://unpkg.com/@angular/common@5.0.1/bundles/common.umd.js/http :/

**Comment by GregKass** [comment]
@victorblq Try this version:

https://plnkr.co/edit/V1nTxG?p=preview

there were some updates that required extra files in the ```systemjs.config.js```

**Comment by victorblq** [comment]
Nice! That works @GregKass , thanks.
