### ISSUE TITLE
ng build --prod && ngc return a bunch of errors

### ISSUE THREAD

**Issue by adichan9791** [angular/material2#7860]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

"ng build --prod && ngc" runs without errors

#### What is the current behavior?

while ng serve and ng build --prod run fine, ng build --prod && ngc return a bunch of errors. The output of the command is as follows

```
Date: 2017-10-17T16:36:55.575Z
Hash: e32fbbabe2475791b6a4
Time: 108878ms
chunk {0} 0.d8d4dfd6eb5a27a5a926.chunk.js (common) 13.5 kB {6}  [rendered]
chunk {1} 1.bd32a4be95e73ca0244b.chunk.js () 562 kB {6}  [rendered]
chunk {2} 2.230ea1229a0e455d7d69.chunk.js () 45.4 kB {6}  [rendered]
chunk {3} 3.6cb3a081b8e804421212.chunk.js () 38 kB {6}  [rendered]
chunk {4} 4.1f50e71d5f79b86b2345.chunk.js () 76.6 kB {6}  [rendered]
chunk {5} polyfills.8ba0ad59110c8694bad7.bundle.js (polyfills) 100 kB {9} [initial] [rendered]
chunk {6} main.3c89496099ad0e0842a2.bundle.js (main) 1.45 MB {8} [initial] [rendered]
chunk {7} styles.ff7f617ac0bed90b7c79.bundle.css (styles) 66.7 kB {9} [initial] [rendered]
chunk {8} vendor.9dd55eb68026cdc34c40.bundle.js (vendor) 1.72 MB [initial] [rendered]
chunk {9} inline.c5d4328845295d738c49.bundle.js (inline) 1.57 kB [entry] [rendered]
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/dialog/typings/index.ngfactory.ts:74:7: Argument of type 'number[][]' is not assignable to parameter of type 'NodeFlags'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/dialog/typings/index.ngfactory.ts:81:69: Argument of type '"mat-dialog-container"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/dialog/typings/index.ngfactory.ts:96:7: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/snack-bar/typings/index.ngfactory.ts:65:7: Argument of type 'number[][]' is not assignable to parameter of type 'NodeFlags'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/snack-bar/typings/index.ngfactory.ts:72:69: Argument of type '"snack-bar-container"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/snack-bar/typings/index.ngfactory.ts:82:21: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/snack-bar/typings/index.ngfactory.ts:94:69: Argument of type '"button"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/snack-bar/typings/index.ngfactory.ts:104:43: Expected 3 arguments, but got 2.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/snack-bar/typings/index.ngfactory.ts:112:29: Expected 3 arguments, but got 2.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/snack-bar/typings/index.ngfactory.ts:114:21: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/snack-bar/typings/index.ngfactory.ts:126:69: Argument of type '"simple-snack-bar"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/snack-bar/typings/index.ngfactory.ts:129:7: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/button/typings/index.ngfactory.ts:43:69: Argument of type '"span"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/button/typings/index.ngfactory.ts:46:9: Argument of type '"div"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/button/typings/index.ngfactory.ts:48:66: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/button/typings/index.ngfactory.ts:51:37: Argument of type '"div"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/button/typings/index.ngfactory.ts:66:69: Argument of type '"button"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/button/typings/index.ngfactory.ts:68:36: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/button/typings/index.ngfactory.ts:81:69: Argument of type '"span"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/button/typings/index.ngfactory.ts:84:9: Argument of type '"div"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/button/typings/index.ngfactory.ts:86:66: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/button/typings/index.ngfactory.ts:89:37: Argument of type '"div"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/button/typings/index.ngfactory.ts:104:69: Argument of type '"a"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/button/typings/index.ngfactory.ts:113:74: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/icon/typings/index.ngfactory.ts:35:69: Argument of type '"mat-icon"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/icon/typings/index.ngfactory.ts:37:57: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:75:69: Argument of type '"mat-month-view"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:89:71: Argument of type 'number[][]' is not assignable to parameter of type 'NodeFlags'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:101:69: Argument of type '"mat-year-view"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:110:69: Argument of type 'number[][]' is not assignable to parameter of type 'NodeFlags'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:123:56: Argument of type '"div"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:125:56: Argument of type '"div"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:127:55: Argument of type '"button"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:138:11: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:139:25: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:140:68: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:141:62: Expected 3 arguments, but got 2.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:142:35: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:144:55: Argument of type '"div"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:146:55: Argument of type '"button"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:157:11: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:158:25: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:159:80: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:160:62: Expected 3 arguments, but got 2.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:161:67: Argument of type '"button"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:172:11: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:173:25: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:174:80: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:176:27: Argument of type '"div"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:185:71: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:187:11: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:189:61: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:192:35: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:221:69: Argument of type '"mat-calendar"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:223:62: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:235:69: Argument of type '"tr"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:237:55: Argument of type '"td"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:239:63: Expected 3 arguments, but got 2.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:251:69: Argument of type '"td"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:254:15: Expected 3 arguments, but got 2.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:265:69: Argument of type '"td"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:278:7: Argument of type '"div"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:280:59: Expected 3 arguments, but got 2.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:301:69: Argument of type '"tr"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:304:35: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:306:81: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:318:60: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:321:7: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:331:69: Argument of type '"div"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:334:7: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:350:76: Argument of type '"mat-datepicker"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:352:63: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:366:23: Argument of type '"mat-calendar"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:381:7: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:382:38: Argument of type 'number[][]' is not assignable to parameter of type 'NodeFlags'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:404:69: Argument of type '"mat-datepicker-content"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:414:21: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:426:69: Argument of type '"button"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:436:81: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:438:21: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:439:76: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:440:82: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:443:7: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:444:21: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:446:7: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:450:9: Argument of type '":svg:path"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:452:23: Argument of type '":svg:path"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:467:69: Argument of type '"mat-datepicker-toggle"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:470:7: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:480:69: Argument of type '"th"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:482:15: Expected 3 arguments, but got 2.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:490:69: Argument of type '"table"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:492:71: Argument of type '"thead"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:494:71: Argument of type '"tr"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:497:36: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:499:41: Argument of type '"tr"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:501:27: Argument of type '"th"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:503:75: Argument of type '"tbody"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:514:11: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:531:69: Argument of type '"mat-month-view"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:533:63: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:545:69: Argument of type '"table"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:547:71: Argument of type '"thead"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:549:71: Argument of type '"tr"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:551:47: Argument of type '"th"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:553:75: Argument of type '"tbody"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:565:7: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:585:69: Argument of type '"mat-year-view"' is not assignable to parameter of type 'number'.
Error at /home/ubuntu/fe-web-user-qa/dist/ngfactory/node_modules/@angular/material/datepicker/typings/index.ngfactory.ts:587:37: Argument of type '0' is not assignable to parameter of type '[string | number, QueryValueType][]'.
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 4.4.5, Material 2.0.0-beta.12, Linux/Ubuntu, Typescript 2.3.3

Package.json contents

```
{
  "name": "first",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "prestart": "ng build --prod && ngc",
    "start": "ts-node --ignore=false src/server.ts",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.4.5",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.4.5",
    "@angular/compiler": "^4.4.5",
    "@angular/core": "^4.4.5",
    "@angular/flex-layout": "^2.0.0-beta.9",
    "@angular/forms": "^4.4.5",
    "@angular/http": "^4.4.5",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "^4.4.5",
    "@angular/platform-browser-dynamic": "^4.4.5",
    "@angular/platform-server": "^4.4.5",
    "@angular/router": "^4.4.5",
    "@swimlane/ngx-charts": "^6.0.2",
    "body-parser": "^1.18.0",
    "core-js": "^2.4.1",
    "d3": "^4.10.0",
    "express": "^4.15.4",
    "md2-accordion": "0.0.1-alpha.0",
    "moment": "^2.18.1",
    "ng2-page-scroll": "^4.0.0-beta.11",
    "ngx-accordion": "0.0.17",
    "ngx-uploader": "^3.3.6",
    "preboot": "^5.0.0",
    "rxjs": "^5.4.3",
    "zone.js": "^0.8.17"
  },
  "devDependencies": {
    "@angular/cli": "1.4.7",
    "@angular/compiler-cli": "^4.4.5",
    "@angular/language-service": "^4.4.5",
    "@angular/platform-server": "^4.4.5",
    "@types/google.analytics": "0.0.35",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "^3.3.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
```

**Comment by willshowell** [comment]
What is it you're trying to do? The CLI has AoT compilation enabled by default for production builds.

**Comment by jelbourn** [comment]
Not really sure what your setup is, but this seems to be related to your environment.
