### ISSUE TITLE
Can't build demo-app at latest commit (8dfe470)

### ISSUE THREAD

**Issue by jplew** [angular/material2#8374]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
run `npm start demo-app` or `gulp serve:devapp` and view the demo app in the browser.

#### What is the current behavior?
Gulp reports an error and exits the build process.

#### What are the steps to reproduce?
`git clone https://github.com/angular/material2.git`
`cd material2`
`npm install`
`gulp serve:devapp`

#### What is the use-case or motivation for changing an existing behavior?
I can serve the demo app perfectly fine from the last release (`5.0.0-rc0` - commit `c13848e71`). So it appears to have broken since then.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
_Gulp_
CLI version 1.4.0
Local version 3.9.1

_Mac OS X_
Sierra 10.12.6

#### Is there anything else we should know?

Here is the error message:

```
$  ./node_modules/.bin/gulp serve:devapp
[01:53:03] Using gulpfile ~/Documents/github/material-new/gulpfile.js
(node:3826) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[01:53:03] Starting 'build:devapp'...
[01:53:03] Starting 'material-moment-adapter:build-no-bundles'...
[01:53:03] Starting 'material:build-no-bundles'...
[01:53:03] Starting 'cdk:build-no-bundles'...
[01:53:03] Starting 'cdk:build:esm:tests'...
[01:53:03] Starting 'cdk:assets:scss'...
[01:53:03] Starting 'cdk:assets:es5-scss'...
[01:53:03] Starting 'cdk:assets:copy-styles'...
[01:53:03] Starting 'cdk:assets:html'...
[01:53:03] Starting ':build:devapp:assets'...
[01:53:03] Finished 'cdk:assets:html' after 194 ms
[01:53:03] Finished 'cdk:assets:es5-scss' after 210 ms
[01:53:03] Finished 'cdk:assets:scss' after 219 ms
[01:53:03] Finished 'cdk:assets:copy-styles' after 211 ms
[01:53:03] Starting 'cdk:assets'...
[01:53:03] Finished 'cdk:assets' after 31 μs
[01:53:04] Finished ':build:devapp:assets' after 541 ms
[01:53:14] Finished 'cdk:build:esm:tests' after 11 s
[01:53:14] Starting 'cdk:assets:inline'...
[01:53:14] Finished 'cdk:assets:inline' after 73 ms
[01:53:14] Finished 'cdk:build-no-bundles' after 11 s
[01:53:14] Starting 'material:build:esm:tests'...
[01:53:14] Starting 'material:assets:scss'...
[01:53:14] Starting 'material:assets:es5-scss'...
[01:53:14] Starting 'material:assets:copy-styles'...
[01:53:14] Starting 'material:assets:html'...
[01:53:16] Finished 'material:assets:html' after 1.2 s
[01:53:16] Finished 'material:assets:copy-styles' after 1.76 s
[01:53:17] Finished 'material:assets:scss' after 2.54 s
[01:53:17] Finished 'material:assets:es5-scss' after 2.63 s
[01:53:17] Starting 'material:assets'...
[01:53:17] Finished 'material:assets' after 2.88 μs
Error: Error: /Users/govinda/Documents/github/material-new/src/lib/input/input.ts:48:1: Error encountered in metadata generated for exported symbol 'MatInput':
 /Users/govinda/Documents/github/material-new/src/lib/input/input.ts:165:48: Metadata collected contains an error that will be reported at runtime: Expression form not supported.
  {"__symbolic":"error","message":"Expression form not supported","line":164,"character":47}
    at /Users/govinda/Documents/github/material-new/node_modules/@angular/compiler-cli/src/metadata/collector.js:663:27
    at Array.forEach (<anonymous>)
    at validateMetadata (/Users/govinda/Documents/github/material-new/node_modules/@angular/compiler-cli/src/metadata/collector.js:651:42)
    at MetadataCollector.getMetadata (/Users/govinda/Documents/github/material-new/node_modules/@angular/compiler-cli/src/metadata/collector.js:508:17)
    at LowerMetadataCache.getMetadataAndRequests (/Users/govinda/Documents/github/material-new/node_modules/@angular/compiler-cli/src/transformers/lower_expressions.js:263:39)
    at LowerMetadataCache.ensureMetadataAndRequests (/Users/govinda/Documents/github/material-new/node_modules/@angular/compiler-cli/src/transformers/lower_expressions.js:209:27)
    at LowerMetadataCache.getRequests (/Users/govinda/Documents/github/material-new/node_modules/@angular/compiler-cli/src/transformers/lower_expressions.js:204:21)
    at /Users/govinda/Documents/github/material-new/node_modules/@angular/compiler-cli/src/transformers/lower_expressions.js:146:36
    at /Users/govinda/Documents/github/material-new/node_modules/typescript/lib/typescript.js:2492:86
    at reduceLeft (/Users/govinda/Documents/github/material-new/node_modules/typescript/lib/typescript.js:2188:30)


Failed to compile  using /Users/govinda/Documents/github/material-new/src/lib/tsconfig-tests.json
[01:53:29] Finished 'material:build:esm:tests' after 14 s
[01:53:29] Starting 'material:assets:inline'...
[01:53:29] Finished 'material:assets:inline' after 108 ms
[01:53:29] Finished 'material:build-no-bundles' after 26 s
[01:53:29] Starting 'material-moment-adapter:build:esm:tests'...
[01:53:29] Starting 'material-moment-adapter:assets:scss'...
[01:53:29] Starting 'material-moment-adapter:assets:es5-scss'...
[01:53:29] Starting 'material-moment-adapter:assets:copy-styles'...
[01:53:29] Starting 'material-moment-adapter:assets:html'...
[01:53:29] Finished 'material-moment-adapter:assets:copy-styles' after 76 ms
[01:53:29] Finished 'material-moment-adapter:assets:scss' after 78 ms
[01:53:29] Finished 'material-moment-adapter:assets:es5-scss' after 77 ms
[01:53:29] Finished 'material-moment-adapter:assets:html' after 76 ms
[01:53:29] Starting 'material-moment-adapter:assets'...
[01:53:29] Finished 'material-moment-adapter:assets' after 6.27 μs
adapter/moment-date-adapter.ts(10,44): error TS2307: Cannot find module '@angular/material'.
adapter/moment-date-adapter.ts(118,37): error TS2339: Property 'locale' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.ts(132,58): error TS2339: Property 'locale' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.ts(143,33): error TS2339: Property 'locale' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.ts(148,46): error TS2339: Property 'locale' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.ts(150,46): error TS2339: Property 'locale' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.ts(191,57): error TS2339: Property 'locale' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-formats.ts(9,30): error TS2307: Cannot find module '@angular/material'.
adapter/index.ts(15,8): error TS2307: Cannot find module '@angular/material'.
adapter/moment-date-adapter.spec.ts(11,64): error TS2307: Cannot find module '@angular/material/core'.
adapter/moment-date-adapter.spec.ts(168,20): error TS2339: Property 'sameDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(267,20): error TS2339: Property 'compareDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(268,20): error TS2339: Property 'compareDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(269,20): error TS2339: Property 'compareDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(270,20): error TS2339: Property 'compareDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(271,20): error TS2339: Property 'compareDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(272,20): error TS2339: Property 'compareDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(273,20): error TS2339: Property 'compareDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(277,20): error TS2339: Property 'clampDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(283,20): error TS2339: Property 'clampDate' does not exist on type 'MomentDateAdapter'.
adapter/moment-date-adapter.spec.ts(289,20): error TS2339: Property 'clampDate' does not exist on type 'MomentDateAdapter'.


Failed to compile  using /Users/govinda/Documents/github/material-new/src/material-moment-adapter/tsconfig-tests.json
[01:53:41] Finished 'material-moment-adapter:build:esm:tests' after 12 s
[01:53:41] Starting 'material-moment-adapter:assets:inline'...
[01:53:41] Finished 'material-moment-adapter:assets:inline' after 65 ms
[01:53:41] Finished 'material-moment-adapter:build-no-bundles' after 38 s
[01:53:41] Starting ':build:devapp:scss'...
[01:53:41] Starting ':build:devapp:ts'...
[01:53:48] Finished ':build:devapp:scss' after 7.07 s
src/demo-app/a11y/button/button-a11y.ts(2,27): error TS2307: Cannot find module '@angular/material'.
src/demo-app/a11y/card/card-a11y.ts(2,27): error TS2307: Cannot find module '@angular/material'.
src/demo-app/a11y/chips/chips-a11y.ts(2,46): error TS2307: Cannot find module '@angular/material'.
src/demo-app/a11y/dialog/dialog-a11y.ts(2,25): error TS2307: Cannot find module '@angular/material'.
src/demo-app/a11y/dialog/dialog-a11y.ts(18,39): error TS7006: Parameter 'result' implicitly has an 'any' type.
src/demo-app/a11y/icon/icon-a11y.ts(2,27): error TS2307: Cannot find module '@angular/material'.
src/demo-app/a11y/sidenav/dual-sidenav-a11y.ts(2,27): error TS2307: Cannot find module '@angular/material/snack-bar'.
src/demo-app/a11y/slide-toggle/slide-toggle-a11y.ts(2,27): error TS2307: Cannot find module '@angular/material'.
src/demo-app/a11y/snack-bar/snack-bar-a11y.ts(2,27): error TS2307: Cannot find module '@angular/material'.
src/demo-app/a11y/table/table-a11y.ts(5,37): error TS2307: Cannot find module '@angular/material'.
src/demo-app/chips/chips-demo.ts(3,33): error TS2307: Cannot find module '@angular/material'.
src/demo-app/datepicker/datepicker-demo.ts(3,39): error TS2307: Cannot find module '@angular/material/datepicker'.
src/demo-app/demo-material-module.ts(33,8): error TS2307: Cannot find module '@angular/material'.
src/demo-app/demo-material-module.ts(34,52): error TS2307: Cannot find module '@angular/material'.
src/demo-app/dialog/dialog-demo.ts(3,73): error TS2307: Cannot find module '@angular/material'.
src/demo-app/icon/icon-demo.ts(3,31): error TS2307: Cannot find module '@angular/material'.
src/demo-app/input/input-demo.ts(3,33): error TS2307: Cannot find module '@angular/material'.
src/demo-app/ripple/ripple-demo.ts(2,25): error TS2307: Cannot find module '@angular/material'.
src/demo-app/select/select-demo.ts(3,31): error TS2307: Cannot find module '@angular/material'.
src/demo-app/snack-bar/snack-bar-demo.ts(8,8): error TS2307: Cannot find module '@angular/material'.
src/demo-app/table/person-data-source.ts(1,37): error TS2307: Cannot find module '@angular/material'.
src/demo-app/table/table-demo.ts(4,57): error TS2307: Cannot find module '@angular/material'.
src/demo-app/table/table-demo.ts(94,55): error TS7006: Parameter 'data' implicitly has an 'any' type.
src/demo-app/table/table-demo.ts(118,52): error TS7006: Parameter 'data' implicitly has an 'any' type.
src/demo-app/tooltip/tooltip-demo.ts(2,31): error TS2307: Cannot find module '@angular/material'.
[01:53:54] ':build:devapp:ts' errored after 13 s
[01:53:54] Error: Process failed with code 1
    at formatError (/Users/govinda/Documents/github/material-new/node_modules/gulp-cli/lib/versioned/^3.7.0/formatError.js:20:10)
    at Gulp.<anonymous> (/Users/govinda/Documents/github/material-new/node_modules/gulp-cli/lib/versioned/^3.7.0/log/events.js:41:15)
    at emitOne (events.js:120:20)
    at Gulp.emit (events.js:210:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/govinda/Documents/github/material-new/node_modules/orchestrator/index.js:264:8)
    at /Users/govinda/Documents/github/material-new/node_modules/orchestrator/index.js:275:23
    at finish (/Users/govinda/Documents/github/material-new/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/govinda/Documents/github/material-new/node_modules/orchestrator/lib/runTask.js:29:3)
    at ChildProcess.<anonymous> (/Users/govinda/Documents/github/material-new/tools/gulp/util/task_helpers.ts:77:21)
    at emitTwo (events.js:125:13)
[01:53:54] 'build:devapp' errored after 51 s
[01:53:54] Error in plugin 'run-sequence(:build:devapp:ts)'
Message:
    Process failed with code 1
Stack:
    at finish (/Users/govinda/Documents/github/material-new/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/Users/govinda/Documents/github/material-new/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:120:20)
    at Gulp.emit (events.js:210:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/govinda/Documents/github/material-new/node_modules/orchestrator/index.js:264:8)
    at /Users/govinda/Documents/github/material-new/node_modules/orchestrator/index.js:275:23
    at finish (/Users/govinda/Documents/github/material-new/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/govinda/Documents/github/material-new/node_modules/orchestrator/lib/runTask.js:29:3)
    at ChildProcess.<anonymous> (/Users/govinda/Documents/github/material-new/tools/gulp/util/task_helpers.ts:77:21)
    at emitTwo (events.js:125:13)
```

**Comment by crisbeto** [comment]
Will be fixed by https://github.com/angular/material2/pull/8367.
