### ISSUE TITLE
adding md-radio-button gives error

### ISSUE THREAD

**Issue by sathishvj** [angular/material2#870]
#### Bug:

I added a bunch of material2 components together.  I was able to add a toolbar and button to my app and see it in the view.  Then I later added @angular-material/radio.  References are there in angular-cli-build.js, package.json, and system-config.ts.

```
import { MD_RADIO_DIRECTIVES } from '@angular2-material/radio';
import { MdUniqueSelectionDispatcher } from '@angular2-material/core';
....
  providers: [MdUniqueSelectionDispatcher],
  directives: [
    APP_SHELL_DIRECTIVES,
    MD_TOOLBAR_DIRECTIVES,
    MD_BUTTON_DIRECTIVES,
    MD_CARD_DIRECTIVES,
    MD_RADIO_DIRECTIVES
  ]

```

I add md-radio-group and there are no issues.  But as soon as I add md-radio-button, there is an error.  
#### What is the current behavior?

build error.
#### What are the steps to reproduce?

http://plnkr.co/edit/BS6JmEIIj639kicEXnWc?p=preview
#### Which versions of Angular, Material, OS, browsers are affected?

material2: 2.0.0-alpha.6
OS: mac
browser: chrome ( but this is on all browsers)
#### Is there anything else we should know?

```
file changed app/app.component.ts
The Broccoli Plugin: [AppShellPlugin] failed with:
Error: Command failed: /bin/sh -c node /Users/user-name/coding/angular2/mobile-toolkit/walnutquiz-web/webui/node_modules/angular2-broccoli-prerender/dist/child_proc.js  --sourceHtml=/Users/user-name/coding/angular2/mobile-toolkit/walnutquiz-web/webui/tmp/app_shell_plugin-input_base_path-dwO6CAEZ.tmp/0/index.html --optionsPath=/Users/user-name/coding/angular2/mobile-toolkit/walnutquiz-web/webui/tmp/app_shell_plugin-input_base_path-dwO6CAEZ.tmp/0/main-app-shell --outputIndexPath=/Users/user-name/coding/angular2/mobile-toolkit/walnutquiz-web/webui/tmp/app_shell_plugin-output_path-efRlZmdx.tmp/index.html
DEPRECATION WARNING: `document` is no longer supported and will be removed in next release. Please use `template`
DEPRECATION WARNING: `Bootloader#serializeApplication` arguments has changed.Please use an `AppConfig` interface {providers: Array<any>, directives: Array<any>, template?: string}
[TypeError: str.replace is not a function]

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:471:12)

The broccoli plugin was instantiated at:
    at AppShellPlugin.Plugin (/Users/username/coding/angular2/mobile-toolkit/walnutquiz-web/webui/node_modules/broccoli-plugin/index.js:10:31)
    at AppShellPlugin.CachingWriter [as constructor] (/Users/username/coding/angular2/mobile-toolkit/walnutquiz-web/webui/node_modules/broccoli-caching-writer/index.js:18:10)
    at new AppShellPlugin (/Users/username/coding/angular2/mobile-toolkit/walnutquiz-web/webui/node_modules/angular2-broccoli-prerender/dist/prerender.js:15:16)
    at Angular2App._buildTree (/Users/username/coding/angular2/mobile-toolkit/walnutquiz-web/webui/node_modules/angular-cli/lib/broccoli/angular2-app.js:161:48)
    at new Angular2App (/Users/username/coding/angular2/mobile-toolkit/walnutquiz-web/webui/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/username/coding/angular2/mobile-toolkit/walnutquiz-web/webui/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/username/coding/angular2/mobile-toolkit/walnutquiz-web/webui/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/username/coding/angular2/mobile-toolkit/walnutquiz-web/webui/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/username/coding/angular2/mobile-toolkit/walnutquiz-web/webui/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/username/coding/angular2/mobile-toolkit/walnutquiz-web/webui/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/username/coding/angular2/mobile-toolkit/walnutquiz-web/webui/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/username/coding/angular2/mobile-toolkit/walnutquiz-web/webui/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/username/coding/angular2/mobile-toolkit/walnutquiz-web/webui/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/username/coding/angular2/mobile-toolkit/walnutquiz-web/webui/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/username/coding/angular2/mobile-toolkit/walnutquiz-web/webui/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:453:9)

```

**Comment by sathishvj** [comment]
Looks like I'm having the same issue with md-checkbox also.  Am I doing something fundamentally wrong?

**Comment by DzmitryShylovich** [comment]
`import { MdRadioButton, MdUniqueSelectionDispatcher, MdRadioGroup } from '@angular2-material/radio';` is the correct import.

Can u reproduce thin in plunkr?

**Comment by sathishvj** [comment]
I had added a plnk but bad formatting made it invisible.  Have fixed it now.

**Comment by jelbourn** [comment]
I think this issue is obsolete. Feel free to open a new issue if there is still a problem.
