### ISSUE TITLE
Mat-menu : ERROR DOMException: Failed to execute 'animate'

### ISSUE THREAD

**Issue by maximeburri** [angular/material2#8756]
#### Bug, feature request, or proposal:
Mat-menu throw an error when click on button (see StackBlitz link).

```
ERROR DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at WebAnimationsPlayer._triggerWebAnimation (https://unpkg.com/@angular/animations@5.0.4/bundles/animations-browser.umd.js:5865:52)
    at WebAnimationsPlayer._buildPlayer (https://unpkg.com/@angular/animations@5.0.4/bundles/animations-browser.umd.js:5828:18)
    at WebAnimationsPlayer.play (https://unpkg.com/@angular/animations@5.0.4/bundles/animations-browser.umd.js:5901:14)
    at TransitionAnimationPlayer.play (https://unpkg.com/@angular/animations@5.0.4/bundles/animations-browser.umd.js:5201:48)
    at eval (https://unpkg.com/@angular/animations@5.0.4/bundles/animations-browser.umd.js:4831:20)
    at Array.forEach (<anonymous>)
    at TransitionAnimationEngine._flushAnimations (https://unpkg.com/@angular/animations@5.0.4/bundles/animations-browser.umd.js:4824:21)
    at TransitionAnimationEngine.flush (https://unpkg.com/@angular/animations@5.0.4/bundles/animations-browser.umd.js:4472:32)
    at InjectableAnimationEngine.AnimationEngine.flush (https://unpkg.com/@angular/animations@5.0.4/bundles/animations-browser.umd.js:5712:32)
    at eval (https://unpkg.com/@angular/platform-browser@5.0.4/bundles/platform-browser-animations.umd.js:401:30)
```

#### What is the expected behavior?
Open the menu with animation, then we can click on mat-menu-item button.

#### What is the current behavior?
On of two times : the click open the menu without animation, then we cannot click on mat-menu-item button, and the hover of mouse doesn't work.

#### What are the steps to reproduce?
[StackBlitz mat-menu code error](https://stackblitz.com/edit/angular-material2-issue-pzqbfc)<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material 5.0.0-rc1

**Comment by crisbeto** [comment]
This seems to work correctly for me. What browser are you seeing the error on?

**Comment by maximeburri** [comment]
The bug was there all day on my project as on the StackBlitz, and after a restart of chrome the bug has disappeared.

Maybe Chrome has updated itself. My current version (without this bug) is **Chrome Mac Version 62.0.3202.94**

**Comment by crisbeto** [comment]
Closing the issue for now. It can be reopened if there's more info.
