### ISSUE TITLE
bug(menu):  trigger _overlayRef not initialised?

### ISSUE THREAD

**Issue by mmrath** [angular/material2#899]
Looks like _overlayRef is never initialised. Which throws the following error

```
Unhandled Promise rejection: EXCEPTION: Error in http://localhost:4200/menu/menu-demo.html:19:6
ORIGINAL EXCEPTION: TypeError: Cannot read property 'dispose' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'dispose' of undefined
    at MdMenuTrigger.destroyMenu (http://localhost:4200/components/menu/menu-trigger.js:53:25)
    at MdMenuTrigger.ngOnDestroy (http://localhost:4200/components/menu/menu-trigger.js:34:62)
    at DebugAppView._View_MenuDemo0.destroyInternal (MenuDemo.template.js:394:28)
    at DebugAppView.AppView.destroyLocal (http://localhost:4200/vendor/@angular/core/src/linker/view.js:175:14)
    at DebugAppView.destroyLocal (http://localhost:4200/vendor/@angular/core/src/linker/view.js:338:43)
    at DebugAppView.AppView._destroyRecurse (http://localhost:4200/vendor/@angular/core/src/linker/view.js:163:14)
    at DebugAppView.AppView._destroyRecurse (http://localhost:4200/vendor/@angular/core/src/linker/view.js:161:25)
    at DebugAppView.AppView.destroy (http://localhost:4200/vendor/@angular/core/src/linker/view.js:149:14)
    at ComponentRef_.destroy (http://localhost:4200/vendor/@angular/core/src/linker/component_factory.js:121:82)
    at RouterOutlet.deactivate (http://localhost:4200/vendor/@angular/router/src/directives/router_outlet.js:45:28)
ERROR CONTEXT:
[object Object] ; Zone: angular ; Task: Promise.then ; Value: 
```

**Comment by kara** [comment]
@mmrath As menu is not yet released, it's only about halfway implemented. I wouldn't suggest using it until all the code goes in :) 

Overlay still needs to be updated to work with menu. There is a pr waiting to go into master that will update it.
