### ISSUE TITLE
Build error with Broccoli Plugin using a Docker Container

### ISSUE THREAD

**Issue by adam2k** [angular/material2#900]
#### Bug, feature request, or proposal:

I hope this isn't out of scope for this repo, but I am have build errors with Broccoli Plugin using a Docker Container.

#### What is the expected behavior?

For the BroccoliMergeTrees to be able to build the angular2 files.

#### What is the current behavior?

The docker container builds, but the during run time the app crashes.

#### What are the steps to reproduce?

The package builds running
    
    npm install
    ng serve

When I build in a docker container using the same commands everything looks to run smoothly and the container builds, but when I run the app and check on my localhost I run into this error:

    Error: EACCES: permission denied, mkdir '/app/tmp/broccoli_merge_trees-output_path-qSkgskNy.tmp'
      at Error (native)
      at Object.fs.mkdirSync (fs.js:922:18)
      at Object.createDirSync (/app/node_modules/mktemp/lib/mktemp.js:114:10)
      at makeTmpDir (/app/node_modules/quick-temp/index.js:45:17)
      at Object.makeOrReuse (/app/node_modules/quick-temp/index.js:21:22)
      at new ReadCompat (/app/node_modules/broccoli-plugin/read_compat.js:17:13)
      at BroccoliMergeTrees.Plugin._initializeReadCompat (/app/node_modules/broccoli-plugin/index.js:130:22)
      at BroccoliMergeTrees.Plugin.read (/app/node_modules/broccoli-plugin/index.js:110:12)
      at /app/node_modules/angular-cli/node_modules/ember-cli-broccoli/lib/builder.js:107:23
      at lib$rsvp$$internal$$tryCatch (/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
      at lib$rsvp$$internal$$invokeCallback (/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
      at /app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
      at lib$rsvp$asap$$flush (/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

    The broccoli plugin was instantiated at: 
      at BroccoliMergeTrees.Plugin (/app/node_modules/broccoli-plugin/index.js:7:31)
      at new BroccoliMergeTrees (/app/node_modules/broccoli-merge-trees/index.js:30:10)
      at module.exports (/app/angular-cli-build.js:26:10)
      at Class.module.exports.Task.extend.setupBroccoliBuilder (/app/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:55:19)
      at Class.module.exports.Task.extend.init (/app/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:89:10)
      at new Class (/app/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
      at Class.module.exports.Task.extend.run (/app/node_modules/angular-cli/node_modules/ember-cli/lib/tasks/serve.js:15:19)
      at /app/node_modules/angular-cli/node_modules/ember-cli/lib/commands/serve.js:64:24
      at lib$rsvp$$internal$$tryCatch (/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
      at lib$rsvp$$internal$$invokeCallback (/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
      at /app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
      at lib$rsvp$asap$$flush (/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

#### What is the use-case or motivation for changing an existing behavior?

To make the docker build process run smoothly

#### Which versions of Angular, Material, OS, browsers are affected?

angular-cli": "^1.0.0-beta.9
@angular/common": "2.0.0-rc.1

Mac OSX, Linux (using docker), All browsers

**Comment by nesukun** [comment]
This is a Docker problem using shared volumes. Using the new Docker for mac betas could alleviate the issue but basically the problem is that, in mac (and windows) docker uses a linux virtual machine and the user ids used for checking fs permissions won't match. there's plenty of information about this issue on the usual places like StackOverflow or Docker's own bug tracker

**Comment by kara** [comment]
The Broccoli plugin is part of the Angular CLI, so we won't be able to help you here. Try submitting the issue in the CLI repo here: https://github.com/angular/angular-cli.
