### ISSUE TITLE
ERROR in Error: Metadata version mismatch for module

### ISSUE THREAD

**Issue by josuevalrob** [angular/material2#9005]
#### Bug
ERROR in Error: Metadata version mismatch for module /angular-site/node_modules/@angular/material/core/typings/index.d.ts, found version 4, expected 3, resolving symbol AppModule in /angular-site/src/app/app.module.ts, resolving symbol AppModule in /angular-site/src/app/app.module.ts

    at syntaxError (/angular-site/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/angular-site/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/angular-site/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/angular-site/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/angular-site/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/angular-site/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/angular-site/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/angular-site/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/angular-site/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/angular-site/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

#### What is the expected behavior?
starting my morning job... 
In the command line: ng serve

I got that error after running the server. 

Then I went to my app.module.ts and comment this: 
```
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { AddTaskComponent } from './add-task/add-task.component';
```
Also I comment from the imports: 
```
    MatTabsModule, 
    MatInputModule,
    MatIconModule
```

After that, I run again the server and it works. 

#### What is the current behavior?

Once my server was running, I uncomment the previous code, so I let it as the original, waiting to see the error again... but nothing happens, the Application was working fine, no error. 

#### What are the steps to reproduce?
You can check the GitHub https://github.com/josuevalrob/tasks
Run the server: ng serve
And the error will come. 
Then you can comment the code mention above, re-run the server, see it works, and uncomment the code, so it will work again. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.4.4
node: 8.6.0
os: darwin x64
@angular/animations: 4.4.6
@angular/cdk: 5.0.1
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/material: 5.0.1
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4

#### Is there anything else we should know?

This is the dependency called in my cdk/package.json
  "_from": "@angular/cdk",
  "_id": "@angular/cdk@5.0.1",

And this one is from the materiasl/package.json
  "_from": "@angular/material@^5.0.1",
  "_id": "@angular/material@5.0.1",

**Comment by spock123** [comment]
Angular Material now requires Angular 5, which itself requires TypeScript 2.4+ and RxJS 5.5.2+

**Comment by josuevalrob** [comment]
How can i update both of them, using angular cli?

**Comment by spock123** [comment]
@josuevalrob  I don't use the CLI myself but I believe CLI 1.5+ uses Angular 5, and CLI 1.6 uses Angular 5.1+.

Upgrade your CLI and you should be good to go.
Others: plz correct me if I'm wrong as I'm not a CLI user.

**Comment by andrewseguin** [comment]
Please refer all troubleshooting questions to our community at StackOverflow, Angular Material mailing lists, Gitter, etc. We try to keep our issues here only open for bugs and feature requests.

**Comment by thorveakshay** [comment]
Try

`npm install @angular/common@latest @angular/compiler@latest @angular/compiler-cli@latest @angular/core@latest @angular/forms@latest @angular/http@latest @angular/platform-browser@latest @angular/platform-browser-dynamic@latest @angular/platform-server@latest @angular/router@latest @angular/animations@latest typescript@latest -g --save`

This will upgrade Angular from any version to latest version. I was also facing some issues this upgrade solved issues.
