### ISSUE TITLE
MdSidenavLayout - inline template:0:177 Bug  with sidenav 

### ISSUE THREAD

**Issue by samirthebti** [angular/material2#916]
I using the Sidenav component and I get this error : 
```

EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in http://localhost:4200/vendor/@angular2-material/sidenav/sidenav.js class MdSidenavLayout - inline template:0:177
ORIGINAL EXCEPTION: TypeError: iterator1.next is not a function
ORIGINAL STACKTRACE:
TypeError: iterator1.next is not a function
    at Object.areIterablesEqual (http://localhost:4200/vendor/@angular/core/src/facade/collection.js:321:31)
    at Object.devModeEqual (http://localhost:4200/vendor/@angular/core/src/change_detection/change_detection_util.js:16:29)
    at checkBinding (http://localhost:4200/vendor/@angular/core/src/linker/view_utils.js:132:33)
    at DebugAppView._View_MdSidenavLayout0.detectChangesInternal (MdSidenavLayout.template.js:64:7)
    at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:269:19)
    at DebugAppView._View_EveyWebAppComponent0.detectChangesInternal (EveyWebAppComponent.template.js:678:8)
    at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:348:44)
ERROR CONTEXT:
[object Object]
```

> MdSidenavLayout - inline template:0:175
> ORIGINAL EXCEPTION: TypeError: iterator1.next is not a function
> ORIGINAL STACKTRACE:
> TypeError: iterator1.next is not a function
>     at Object.areIterablesEqual

**Comment by jelbourn** [comment]
@samirthebti Please follow our issue template, which includes providing the version of Angular MAterial you are using. Feel free to file a new issue with all of the relevant information.
