### ISSUE TITLE
Edge browser: Object doesn't support property or method 'subscribe'

### ISSUE THREAD

**Issue by loganfreeman** [angular/material2#9265]
#### Bug, feature request, or proposal:

run karma test on Edge browser using the following command:

```
ng test --single-run --reporters=spec --browsers=Edge
```

with following package.json

```
    "@angular/animations": "^4.0.0",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/flex-layout": "^2.0.0-rc.1",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.8",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ngrx/store": "^4.1.1",
    "angulartics2": "^4.5.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.4",
    "rxjs": "^5.1.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.19"
```

```
	TypeError: Object doesn't support property or method 'subscribe'
	   at MatFormField.prototype.ngAfterContentInit (http://localhost:9876/_karma_webpack_/vendor.bundle.js:135149:9)
	   at callProviderLifecycles (http://localhost:9876/_karma_webpack_/vendor.bundle.js:107464:9)
	   at callElementProvidersLifecycles (http://localhost:9876/_karma_webpack_/vendor.bundle.js:107441:13)
	   at callLifecycleHooksChildrenFirst (http://localhost:9876/_karma_webpack_/vendor.bundle.js:107425:17)
	   at checkAndUpdateView (http://localhost:9876/_karma_webpack_/vendor.bundle.js:108548:5)
	   at callViewAction (http://localhost:9876/_karma_webpack_/vendor.bundle.js:108893:21)
	   at execEmbeddedViewsAction (http://localhost:9876/_karma_webpack_/vendor.bundle.js:108851:17)
	   at checkAndUpdateView (http://localhost:9876/_karma_webpack_/vendor.bundle.js:108546:5)
	   at callViewAction (http://localhost:9876/_karma_webpack_/vendor.bundle.js:108893:21)
	   at execComponentViewsAction (http://localhost:9876/_karma_webpack_/vendor.bundle.js:108825:13)


	TypeError: Object doesn't support property or method 'subscribe'
	   at MatFormField.prototype.ngAfterContentInit (http://localhost:9876/_karma_webpack_/vendor.bundle.js:135149:9)
	   at callProviderLifecycles (http://localhost:9876/_karma_webpack_/vendor.bundle.js:107464:9)
	   at callElementProvidersLifecycles (http://localhost:9876/_karma_webpack_/vendor.bundle.js:107441:13)
	   at callLifecycleHooksChildrenFirst (http://localhost:9876/_karma_webpack_/vendor.bundle.js:107425:17)
	   at checkAndUpdateView (http://localhost:9876/_karma_webpack_/vendor.bundle.js:108548:5)
	   at callViewAction (http://localhost:9876/_karma_webpack_/vendor.bundle.js:108893:21)
	   at execComponentViewsAction (http://localhost:9876/_karma_webpack_/vendor.bundle.js:108825:13)
	   at checkAndUpdateView (http://localhost:9876/_karma_webpack_/vendor.bundle.js:108551:5)
	   at callWithDebugContext (http://localhost:9876/_karma_webpack_/vendor.bundle.js:109761:9)
	   at debugCheckAndUpdateView (http://localhost:9876/_karma_webpack_/vendor.bundle.js:109301:5)
```

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

**Comment by crisbeto** [comment]
This looks like an issue with your testing setup. If you're testing a component with a form field, make sure to include the necessary modules (e.g. `MatInputModule` and `MatFormFieldModule` if you're using an input).

**Comment by loganfreeman** [comment]
I added the module as you said, but the exception remains.

**Comment by loganfreeman** [comment]
It doesn't happen when using other browsers such as Chrome, PhantomJs.

**Comment by loganfreeman** [comment]
It happens here:

```
        // Subscribe to changes in the child control state in order to update the form field UI.
        this._control.stateChanges.pipe(startWith(/** @type {?} */ ((null)))).subscribe(function () {
            _this._validatePlaceholders();
            _this._syncDescribedByIds();
            _this._changeDetectorRef.markForCheck();
        });
```

**Comment by loganfreeman** [comment]
I figured out that it needs rxjs 5.5. the pipe is introduced at 5.5
