### ISSUE TITLE
alpha.6-3 broken

### ISSUE THREAD

**Issue by udos86** [angular/material2#954]
#### Bug, feature request, or proposal: 
Bug

#### What is the expected behavior? 
SystemJS / Webpack loading Angular 2 Material properly

#### What is the current behavior? 

When updating to  alpha.6-3, SystemJS / Webpack fails loading Angular 2 Material with the following error:
```
Error: (SystemJS) core_1.NgModule is not a function
	TypeError: core_1.NgModule is not a function
	    at eval (http://localhost:3000/node_modules/@angular2-material/core/rtl/dir.js:70:16)
	    at Object.eval (http://localhost:3000/node_modules/@angular2-material/core/rtl/dir.js:77:2)
	    at eval (http://localhost:3000/node_modules/@angular2-material/core/rtl/dir.js:80:4)
	    at eval (http://localhost:3000/node_modules/@angular2-material/core/rtl/dir.js:81:3)
```

Karma / PhantomJS also stop executing with the following error prompt:
```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  {
    "stack": null,
    "originalErr": {
      "line": 70,
      "stack": "\n\n\neval code\neval@[native code]\n__exec@node_modules/systemjs/dist/system.src.js:1559:18\nexecute@node_modules/systemjs/dist/system.src.js:4020:22\nlinkDynamicModule@node_modules/systemjs/dist/system.src.js:3296:36\ngetModule@node_modules/systemjs/dist/system.src.js:3264:26\nnode_modules/systemjs/dist/system.src.js:3300:25\nrequire@node_modules/systemjs/dist/system.src.js:3984:34\n\n\neval code\neval@[native code]\n__exec@node_modules/systemjs/dist/system.src.js:1559:18\nexecute@node_modules/systemjs/dist/system.src.js:4020:22\nlinkDynamicModule@node_modules/systemjs/dist/system.src.js:3296:36\ngetModule@node_modules/systemjs/dist/system.src.js:3264:26\nnode_modules/systemjs/dist/system.src.js:3300:25\nrequire@node_modules/systemjs/dist/system.src.js:3984:34\n\n\neval code\neval@[native code]\n__exec@node_modules/systemjs/dist/system.src.js:1559:18\nexecute@node_modules/systemjs/dist/system.src.js:4020:22\nlinkDynamicModule@node_modules/systemjs/dist/system.src.js:3296:36\ngetModule@node_modules/systemjs/dist/system.src.js:3264:26\nnode_modules/systemjs/dist/system.src.js:3300:25\nrequire@node_modules/systemjs/dist/system.src.js:3984:34\n\n\neval code\neval@[native code]\n__exec@node_modules/systemjs/dist/system.src.js:1559:18\nexecute@node_modules/systemjs/dist/system.src.js:4020:22\nlinkDynamicModule@node_modules/systemjs/dist/system.src.js:3296:36\nlink@node_modules/systemjs/dist/system.src.js:3135:28\nexecute@node_modules/systemjs/dist/system.src.js:3506:17\ndoDynamicExecute@node_modules/systemjs/dist/system.src.js:772:32\nlink@node_modules/systemjs/dist/system.src.js:970:36\ndoLink@node_modules/systemjs/dist/system.src.js:629:11\nupdateLinkSetOnLoad@node_modules/systemjs/dist/system.src.js:675:24\nnode_modules/systemjs/dist/system.src.js:491:30\ninvoke@node_modules/zone.js/dist/zone.js:323:34\nrun@node_modules/zone.js/dist/zone.js:216:50\nnode_modules/zone.js/dist/zone.js:571:61\ninvokeTask@node_modules/zone.js/dist/zone.js:356:43\nrunTask@node_modules/zone.js/dist/zone.js:256:58\ndrainMicroTaskQueue@node_modules/zone.js/dist/zone.js:474:43\ninvoke@node_modules/zone.js/dist/zone.js:426:41\nnode_modules/zone.js/dist/zone.js:93:33\ninvokeTask@node_modules/zone.js/dist/zone.js:356:43\nrunTask@node_modules/zone.js/dist/zone.js:256:58\ninvoke@node_modules/zone.js/dist/zone.js:423:41"
    },
    "line": 797,
    "sourceURL": "node_modules/systemjs/dist/system.src.js"
  }
```

#### What are the steps to reproduce?

Update to alpha.6-3

**Comment by PrabhBaath** [comment]
+1

**Comment by dreday966** [comment]
I met this issue,too.

**Comment by bgauvey** [comment]
ditto. Same error

Using webpack instead of SystemJS.

**Comment by jelbourn** [comment]
alpha.6-3 is published under the `@experimental` label on npm. Only the `@latest` label represents our current release.

**Comment by dreday966** [comment]
I am on alpha.6-2,and I got also met this issue.

**Comment by a5hik** [comment]
same here with 6-3

**Comment by kurtommy** [comment]
@jelbourn I'm trying to use md-menu. After `npm i -S @angular2-material/menu@2.0.0-alpha.6`
```
npm ERR! No compatible version found: @angular2-material/menu@2.0.0-alpha.6
npm ERR! Valid install targets:
npm ERR! 2.0.0-alpha.6-3, 2.0.0-alpha.6-2
```
but if i upgrade `@angular2-material` to `@2.0.0-alpha.6-3` I get the error mentioned above.
There is an `md-menu` compatible with `@angular2-material/core@2.0.0-alpha.6` ?

**Comment by briankoech** [comment]
I get this error trying to use `md-input` .

**Comment by jelbourn** [comment]
alpha.7 is released now.

alpha.6-2 and alpha.6-3 were never published under the `@latest` tag on npm, only the `@experimental` tag.
